/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fsoporte.java
 *
 * Created on 08-jun-2011, 6:45:30
 */
package formas;

import com.mysql.jdbc.Connection;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author ibrahinaraujo
 */
public class bienes extends javax.swing.JFrame {
    public static Connection conn1;
    public static java.sql.Statement sql;
    private ResultSet rs;
    private int opcion;
    public  static int swe = 0;
    public static String Nregistro,fecha ;    
    public static String txtopi,txtopm,txtope;
    public String fecrec,fecdes,fecconte,Mfecha,mcode,mdes,Medoreg,Void;    
    public static String fileName;
    proceso PROCE = new proceso();
    
    /** Creates new form fsoporte */
    public bienes() {
           initComponents();
           setIconImage (new ImageIcon("./imagenes/ibraico.png").getImage());
           setLocationRelativeTo(null);
           Cfecharec.getDateEditor().setEnabled(false);
           Cfecharec.requestFocus();
           Cfecharec.setMinSelectableDate(new Date());
           JTableHeader cabeceraTabla1 = Tabla1.getTableHeader();
           cabeceraTabla1.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 12));
           cabeceraTabla1.setBackground(new java.awt.Color(0, 102, 153));
           cabeceraTabla1.setForeground(new java.awt.Color(255,255, 255));
           JTableHeader cabeceraTabla2 = Tabla2.getTableHeader();
           cabeceraTabla2.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 12));
           cabeceraTabla2.setBackground(new java.awt.Color(0, 102, 153));
           cabeceraTabla2.setForeground(new java.awt.Color(255,255, 255));   
           JTableHeader cabeceraTabla3 = Tabla3.getTableHeader();
           cabeceraTabla3.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 12));
           cabeceraTabla3.setBackground(new java.awt.Color(0, 102, 153));
           cabeceraTabla3.setForeground(new java.awt.Color(255,255, 255));   
           cargar_servicios();   
           cargar_reporte();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btonincluir = new javax.swing.JButton();
        btoneliminar = new javax.swing.JButton();
        btonmodificar = new javax.swing.JButton();
        btoncancelar = new javax.swing.JButton();
        btonaceptar = new javax.swing.JButton();
        btonsalir = new javax.swing.JButton();
        aviso = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Ficha = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        Codigo = new javax.swing.JLabel();
        fechareg = new javax.swing.JLabel();
        servicio = new javax.swing.JLabel();
        Bien = new javax.swing.JLabel();
        Seccion = new javax.swing.JLabel();
        subgrupos = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        Bunitario = new javax.swing.JLabel();
        Btotal = new javax.swing.JLabel();
        Cnumero = new javax.swing.JTextField();
        Cfecharec = new com.toedter.calendar.JDateChooser();
        Ccodserv = new javax.swing.JFormattedTextField();
        Ccodbien = new javax.swing.JComboBox();
        Cnumbien = new javax.swing.JTextField();
        Cservicio = new javax.swing.JFormattedTextField();
        subgrupo = new javax.swing.JFormattedTextField();
        seccion = new javax.swing.JFormattedTextField();
        cantidad = new javax.swing.JFormattedTextField();
        jScroldescrip = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        unitario = new javax.swing.JFormattedTextField();
        total = new javax.swing.JFormattedTextField();
        tabla1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("REGISTRO DE BIENES");
        setBackground(new java.awt.Color(0, 102, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(null);

        btonincluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btonincluir.setForeground(new java.awt.Color(0, 0, 102));
        btonincluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/incluir.png"))); // NOI18N
        btonincluir.setText("Incluir");
        btonincluir.setToolTipText("Incluir Registro");
        btonincluir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btonincluir.setIconTextGap(10);
        btonincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonincluirActionPerformed(evt);
            }
        });
        jPanel1.add(btonincluir);
        btonincluir.setBounds(10, 10, 120, 30);

        btoneliminar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btoneliminar.setForeground(new java.awt.Color(0, 0, 102));
        btoneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminar.png"))); // NOI18N
        btoneliminar.setText("Borrar");
        btoneliminar.setToolTipText("Eliminar Registro");
        btoneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btoneliminar.setMaximumSize(new java.awt.Dimension(87, 23));
        btoneliminar.setMinimumSize(new java.awt.Dimension(87, 23));
        btoneliminar.setPreferredSize(new java.awt.Dimension(87, 23));
        btoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btoneliminar);
        btoneliminar.setBounds(10, 50, 120, 30);

        btonmodificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btonmodificar.setForeground(new java.awt.Color(0, 0, 102));
        btonmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btonmodificar.setText("Modificar");
        btonmodificar.setToolTipText("Modificar Registro");
        btonmodificar.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        btonmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btonmodificar.setIconTextGap(5);
        btonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonmodificarActionPerformed(evt);
            }
        });
        jPanel1.add(btonmodificar);
        btonmodificar.setBounds(10, 90, 120, 30);

        btoncancelar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btoncancelar.setForeground(new java.awt.Color(0, 51, 102));
        btoncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/redo.png"))); // NOI18N
        btoncancelar.setText("Cancelar");
        btoncancelar.setToolTipText("Cancelar Registro");
        btoncancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btoncancelar.setIconTextGap(0);
        btoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoncancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btoncancelar);
        btoncancelar.setBounds(10, 130, 120, 30);

        btonaceptar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btonaceptar.setForeground(new java.awt.Color(0, 0, 102));
        btonaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        btonaceptar.setText("Guardar");
        btonaceptar.setToolTipText("Aceptar Registro");
        btonaceptar.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        btonaceptar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btonaceptar.setIconTextGap(14);
        btonaceptar.setMaximumSize(new java.awt.Dimension(87, 23));
        btonaceptar.setMinimumSize(new java.awt.Dimension(87, 23));
        btonaceptar.setPreferredSize(new java.awt.Dimension(87, 23));
        btonaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonaceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btonaceptar);
        btonaceptar.setBounds(10, 170, 120, 30);

        btonsalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btonsalir.setForeground(new java.awt.Color(0, 0, 102));
        btonsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btonsalir.setText("Salida");
        btonsalir.setToolTipText("Salir de Cargo");
        btonsalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btonsalir.setIconTextGap(10);
        btonsalir.setPreferredSize(new java.awt.Dimension(83, 23));
        btonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btonsalir);
        btonsalir.setBounds(10, 210, 120, 30);

        aviso.setFont(new java.awt.Font("Arial", 1, 12));
        aviso.setForeground(new java.awt.Color(0, 0, 153));
        aviso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aviso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(aviso);
        aviso.setBounds(10, 400, 110, 21);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(null);

        Ficha.setFont(new java.awt.Font("Arial", 1, 12));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.setLayout(null);

        Codigo.setFont(new java.awt.Font("Tahoma", 1, 12));
        Codigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Codigo.setText("Codigo");
        jPanel3.add(Codigo);
        Codigo.setBounds(10, 12, 43, 15);

        fechareg.setFont(new java.awt.Font("Arial", 1, 12));
        fechareg.setText("Fecha_Rec");
        jPanel3.add(fechareg);
        fechareg.setBounds(188, 12, 70, 15);

        servicio.setFont(new java.awt.Font("Tahoma", 1, 12));
        servicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        servicio.setText("Servicio");
        jPanel3.add(servicio);
        servicio.setBounds(10, 40, 47, 15);

        Bien.setFont(new java.awt.Font("Tahoma", 1, 12));
        Bien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bien.setText("Bien");
        jPanel3.add(Bien);
        Bien.setBounds(10, 70, 26, 15);

        Seccion.setFont(new java.awt.Font("Tahoma", 1, 12));
        Seccion.setText("Seccion");
        jPanel3.add(Seccion);
        Seccion.setBounds(10, 133, 80, 15);

        subgrupos.setFont(new java.awt.Font("Tahoma", 1, 12));
        subgrupos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subgrupos.setText("Sub Grupo");
        jPanel3.add(subgrupos);
        subgrupos.setBounds(10, 100, 90, 15);

        Cantidad.setFont(new java.awt.Font("Tahoma", 1, 12));
        Cantidad.setText("Cantidad");
        jPanel3.add(Cantidad);
        Cantidad.setBounds(10, 162, 70, 15);

        Descripcion.setFont(new java.awt.Font("Tahoma", 1, 12));
        Descripcion.setText("Descripcion");
        jPanel3.add(Descripcion);
        Descripcion.setBounds(10, 200, 90, 15);

        Bunitario.setFont(new java.awt.Font("Tahoma", 1, 12));
        Bunitario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bunitario.setText("Valor Unit.");
        jPanel3.add(Bunitario);
        Bunitario.setBounds(330, 75, 66, 15);

        Btotal.setFont(new java.awt.Font("Tahoma", 1, 12));
        Btotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btotal.setText("Valor Total");
        jPanel3.add(Btotal);
        Btotal.setBounds(330, 105, 68, 15);

        Cnumero.setBackground(new java.awt.Color(255, 255, 102));
        Cnumero.setEditable(false);
        Cnumero.setFont(new java.awt.Font("Arial", 1, 12));
        Cnumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cnumero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.add(Cnumero);
        Cnumero.setBounds(140, 12, 40, 20);

        Cfecharec.setFont(new java.awt.Font("Tahoma", 1, 12));
        Cfecharec.setMinSelectableDate(new java.util.Date(-62135765898000L));
        Cfecharec = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "####-##-##", '_');
        Cfecharec.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel3.add(Cfecharec);
        Cfecharec.setBounds(260, 10, 110, 20);

        Ccodserv.setBackground(new java.awt.Color(255, 255, 102));
        Ccodserv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Ccodserv.setEditable(false);
        Ccodserv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ccodserv.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel3.add(Ccodserv);
        Ccodserv.setBounds(140, 40, 40, 23);

        Ccodbien.setFont(new java.awt.Font("Tahoma", 1, 12));
        Ccodbien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BE", "BN" }));
        Ccodbien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.add(Ccodbien);
        Ccodbien.setBounds(140, 70, 50, 25);

        Cnumbien.setFont(new java.awt.Font("Arial", 1, 12));
        Cnumbien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.add(Cnumbien);
        Cnumbien.setBounds(200, 70, 120, 23);

        Cservicio.setBackground(new java.awt.Color(255, 255, 102));
        Cservicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Cservicio.setEditable(false);
        Cservicio.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel3.add(Cservicio);
        Cservicio.setBounds(190, 40, 320, 23);

        subgrupo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        subgrupo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        subgrupo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        subgrupo.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(subgrupo);
        subgrupo.setBounds(140, 100, 30, 23);

        seccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        seccion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        seccion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        seccion.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(seccion);
        seccion.setBounds(140, 130, 30, 23);

        cantidad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cantidad.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(cantidad);
        cantidad.setBounds(140, 160, 30, 23);

        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Arial", 1, 12));
        descripcion.setRows(5);
        descripcion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScroldescrip.setViewportView(descripcion);

        jPanel3.add(jScroldescrip);
        jScroldescrip.setBounds(140, 190, 380, 50);

        unitario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        unitario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        unitario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        unitario.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(unitario);
        unitario.setBounds(400, 70, 110, 23);

        total.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        total.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(total);
        total.setBounds(400, 100, 110, 23);

        Tabla1.setFont(new java.awt.Font("Tahoma", 1, 12));
        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "oid", "BIEN", "CODIGO", "SUB.GRU", "SECCION", "CANTIDAD", "UNITARIO", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Tabla1MouseReleased(evt);
            }
        });
        Tabla1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tabla1KeyReleased(evt);
            }
        });
        tabla1.setViewportView(Tabla1);
        Tabla1.getColumnModel().getColumn(0).setMinWidth(0);
        Tabla1.getColumnModel().getColumn(0).setPreferredWidth(0);
        Tabla1.getColumnModel().getColumn(0).setMaxWidth(0);
        Tabla1.getColumnModel().getColumn(1).setMinWidth(100);
        Tabla1.getColumnModel().getColumn(1).setPreferredWidth(100);
        Tabla1.getColumnModel().getColumn(1).setMaxWidth(100);
        Tabla1.getColumnModel().getColumn(2).setMinWidth(80);
        Tabla1.getColumnModel().getColumn(2).setPreferredWidth(80);
        Tabla1.getColumnModel().getColumn(2).setMaxWidth(80);

        jPanel3.add(tabla1);
        tabla1.setBounds(10, 250, 510, 180);

        Ficha.addTab("REGISTRO DEL BIEN", jPanel3);

        jPanel4.setLayout(null);

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tabla2KeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(Tabla2);
        Tabla2.getColumnModel().getColumn(0).setMinWidth(100);
        Tabla2.getColumnModel().getColumn(0).setPreferredWidth(100);
        Tabla2.getColumnModel().getColumn(0).setMaxWidth(100);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(20, 20, 500, 410);

        Ficha.addTab("SERVICIOS", jPanel4);

        jPanel5.setLayout(null);

        Tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REPORTE", "DESCRIPCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tabla3KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla3);
        Tabla3.getColumnModel().getColumn(0).setMinWidth(0);
        Tabla3.getColumnModel().getColumn(0).setPreferredWidth(0);
        Tabla3.getColumnModel().getColumn(0).setMaxWidth(0);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 470, 350);

        Ficha.addTab("LISTADOS", jPanel5);

        jPanel2.add(Ficha);
        Ficha.setBounds(10, 10, 540, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar(){
      Cnumero.setText("");  
      Cfecharec.setDate(null);
      cantidad.setValue(0);
      subgrupo.setValue(0); 
      Ccodserv.setText(null);
      Cservicio.setText(null);       
      Ccodbien.setSelectedItem(null);
      Cnumbien.setText(null);
      seccion.setValue(0);   
      descripcion.setText(null);
      unitario.setValue(0);
      total.setValue(0);     
      aviso.setText(null);
  }
    
   private void cargar_tabla() {
        String valor  =  Ccodserv.getText();
        DefaultTableModel tr = (DefaultTableModel)Tabla1.getModel();
        try {
             rs = sql.executeQuery("select * from bienes inner join servicios on(servicios.cod_serv = bienes.codserv) where bienes.codserv="+valor+" and bienes.edo_reg ='A'  ");
             while (rs.next()) {
                    Integer vreg     = rs.getInt("oid");
                    String  vbien    = rs.getString("codbien")+"-"+rs.getString("numbien");
                    String  vcodserv = rs.getString("codserv");
                    String  vsubgrupo= rs.getString("subgrupo");
                    String  vseccion = rs.getString("seccion");
                    String  vcantidad= rs.getString("cantidad");
                    String  vunitario= rs.getString("valorunit");
                    String  vtotal   = rs.getString("valortotal");
                    tr.addRow(new Object[]{new Integer (vreg),vbien,vcodserv,vsubgrupo,vseccion,vcantidad,vunitario,vtotal});
                    Tabla1.setModel(tr);
                    TableColumn column = null;
             }
            } catch (Exception e) { }
    }
   
   
   private void cargar_servicios() {
        DefaultTableModel tr = (DefaultTableModel)Tabla2.getModel();
        try {
             rs = sql.executeQuery("select * from servicios order by cod_serv");
             while (rs.next()) {                                       
                    String vcodserv = rs.getString("cod_serv");
                    String vdenserv = rs.getString("den_serv").trim();                   
                    tr.addRow(new Object[]{vcodserv,vdenserv});
                    Tabla2.setModel(tr);
                    TableColumn column = null;
            }
            } catch (Exception e) { }            
        }
   
   private void cargar_reporte() {
        DefaultTableModel tr = (DefaultTableModel)Tabla3.getModel();
        try {
             rs = sql.executeQuery("select * from repolist where status = 'BIEN' order by descrip");
             while (rs.next()) {                                       
                    String vcodigo = rs.getString("codigo");
                    String vdescrip= rs.getString("descrip").trim();                   
                    tr.addRow(new Object[]{vcodigo,vdescrip});
                    Tabla3.setModel(tr);
                    TableColumn column = null;
            }
            } catch (Exception e) { }            
        }
   
    public void buscar(String M1){
        try
          {    
           rs = sql.executeQuery("select * from bienes where oid="+M1+" "); 
           if(rs.next()) {              
              Cnumero.setText(rs.getString("oid")); 
              Cfecharec.setDate(PROCE.Vfecha(rs.getDate("fecharec")));            
              Ccodbien.setSelectedItem(rs.getString("codbien"));
              Cnumbien.setText(rs.getString("numbien"));              
              subgrupo.setValue(rs.getDouble("subgrupo"));
              seccion.setValue(rs.getDouble("seccion"));
              cantidad.setValue(rs.getDouble("cantidad"));             
              descripcion.setText(rs.getString("descripcion").toUpperCase().trim());    
              unitario.setValue(rs.getDouble("valorunit"));    
              total.setValue(rs.getDouble("valortotal"));              
          }
        }
        catch (Exception e) { }      
  }  
  public void busserv(){
        try
          {    
           rs = sql.executeQuery("select * from servicios where cod_serv="+Ccodserv.getText()+" "); 
           if(rs.next()) {              
              Cservicio.setText(rs.getString("den_serv").trim());                
                         
          }
        }
        catch (Exception e) { }      
  }  
  
public String Gfecha(Date f2){
       String fechaS;
       Date fecha1 = f2;
       if (fecha1 == null){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            try {
                fecha1  = sdf.parse("0001/01/01");             
            } catch (ParseException ex) {
                Logger.getLogger(proceso.class.getName()).log(Level.SEVERE, null, ex);
            }
            fechaS = sdf.format(fecha1);
            }else {
              SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
              fechaS = sdf.format(fecha1);
       }       
       return fechaS;
}
    
    private void btonincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonincluirActionPerformed
      opcion = 1;
      aviso.setText("INCLUIR");
      btonmodificar.setEnabled(false);
      btoneliminar.setEnabled(false);
      btoncancelar.setEnabled(true);
      btonaceptar.setEnabled(true);
    }//GEN-LAST:event_btonincluirActionPerformed

    private void btoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoneliminarActionPerformed
      if ( swe != 0){
          opcion = 3;
          swe = 1;
          aviso.setText("ELIMINACION");
          btoncancelar.setEnabled(true);
          btonaceptar.setEnabled(true);
      }
}//GEN-LAST:event_btoneliminarActionPerformed

    private void btonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonmodificarActionPerformed
      if ( swe != 0){
          opcion = 2;
          swe = 1;
          aviso.setText("MODIFICAR");
          btoncancelar.setEnabled(true);
          btonaceptar.setEnabled(true);
        }//GEN-LAST:event_btonmodificarActionPerformed
    }
        private void btonaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonaceptarActionPerformed
        
                      
            // Ingreso de Registro
           
            if(opcion == 1) {      
             
                try {           
                    String vedoreg = "A";
                    String vfecharec=Gfecha(Cfecharec.getDate());
                    String vcodserv= Ccodserv.getText();
                    String vsubgrupo= subgrupo.getText().toUpperCase().trim();
                    String vseccion= seccion.getText().toUpperCase().trim();
                    String vcantidad= cantidad.getText().toUpperCase().trim();
                    String vcodbien= (String) Ccodbien.getSelectedItem();
                    String vnumbien= Cnumbien.getText();                    
                    String vdescripcion = descripcion.getText().toUpperCase().trim();                                     
                    String vvalorunit = unitario.getText().toUpperCase().trim();
                    String vvalortotal= total.getText().toUpperCase().trim();                  
                    
                    sql.executeUpdate("insert into bienes (edo_reg,"
                                                            + "fecharec,"
                                                            + "codserv,"
                                                            + "codbien,"                                                           
                                                            + "numbien,"
                                                            + "subgrupo,"
                                                            + "seccion,"
                                                            + "cantidad,"
                                                            + "descripcion,"                                                         
                                                            + "valorunit,"                                                            
                                                            + "valortotal) "+
                                                  "values('"+vedoreg+"',"
                                                            + "'"+vfecharec+"',"
                                                            + "'"+vcodserv+"',"
                                                            + "'"+vcodbien+"',"
                                                            + "'"+vnumbien+"',"
                                                            + "'"+vsubgrupo+"',"
                                                            + "'"+vseccion+"',"
                                                            + "'"+vcantidad+"',"
                                                            + "'"+vdescripcion+"',"                                                            
                                                            + "'"+vvalorunit+"',"                                                            
                                                            + "'"+vvalortotal+"')");
                 
                } catch(Exception e) { }
            }
            
            // Actualizacion del Registro
            if(opcion == 2) {
                int fila=Tabla1.getSelectedRow();
                Integer Numero = (Integer) Tabla1.getValueAt(fila,0);                
                int a=JOptionPane.showConfirmDialog(this,"Desea Modificar el Registro" +
                        "","A T E N C I O N",JOptionPane.ERROR_MESSAGE);
                if(a==0) {
                    opcion=0;
                    swe = 0;
                    try {     

                        sql.executeUpdate("update bienes " +
                                       " set codserv = '"+Ccodserv.getText().toUpperCase().trim()+"'"+                                       
                                       ",fecharec    = '"+Gfecha(Cfecharec.getDate())+"'"+
                                       ",codserv     = '"+Ccodserv.getText()+"'"+  
                                       ",codbien     = '"+Ccodbien.getSelectedItem()+"'"+
                                       ",numbien     = '"+Cnumbien.getText()+"'"+ 
                                       ",subgrupo    = '"+subgrupo.getText().toUpperCase().trim()+"'"+
                                       ",seccion     = '"+seccion.getText().toUpperCase().trim()+"'"+
                                       ",cantidad    = '"+cantidad.getText().toUpperCase().trim()+"'"+                                    
                                       ",descripcion = '"+descripcion.getText().toUpperCase().trim()+"'"+
                                       ",valorunit   = '"+unitario.getValue()+"'"+
                                       ",valortotal  = '"+total.getValue()+"'"+                                      
                                    "where oid       = '"+Numero+"'");                        
                    }                    
                    catch(Exception e) { }
                }
            }
            
            // Eliminacion del Registro
            if(opcion == 3) {
                int a=JOptionPane.showConfirmDialog(this,"Desea Eliminar el Registro" +
                        "","A T E N C I O N",JOptionPane.ERROR_MESSAGE);
                if(a==0) {
                    
                    try {                       
                                          
                        sql.executeUpdate("UPDATE bienes SET edo_reg  ='D' WHERE oid ='"+Cnumero.getText()+"' ");
                        
                        JOptionPane.showMessageDialog(this,"OPERACION EXITOSA","A T E N C I O N",JOptionPane.INFORMATION_MESSAGE);
                    }
                    
                    catch(Exception e) { }
                }
            }
            swe = 0;           
            DefaultTableModel tr = (DefaultTableModel)Tabla1.getModel();
            tr.setRowCount(0);
            cargar_tabla();
}//GEN-LAST:event_btonaceptarActionPerformed

        private void btonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonsalirActionPerformed
        try {
            limpiar();
            dispose();
            rs.close();          
        } catch (SQLException ex) {
            Logger.getLogger(bienes.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btonsalirActionPerformed

        private void Tabla1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabla1KeyReleased
            swe = 1;
            int fila=Tabla1.getSelectedRow();
            String vregi=Tabla1.getValueAt(fila,0).toString(); 
            String vcode=Tabla1.getValueAt(fila,2).toString();  
            Nregistro = vregi;
            Ccodserv.setText(vcode);
            buscar(Nregistro);  
            permiso();
        }//GEN-LAST:event_Tabla1KeyReleased

        private void Tabla1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseReleased
            swe = 1;
            int fila=Tabla1.getSelectedRow();
            String vregi=Tabla1.getValueAt(fila,0).toString(); 
            String vcode=Tabla1.getValueAt(fila,2).toString();            
            Nregistro = vregi;
            Ccodserv.setText(vcode);
            buscar(Nregistro);    
            permiso();
        }//GEN-LAST:event_Tabla1MouseReleased

        private void Tabla2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabla2KeyPressed
            if(evt.getKeyCode()==KeyEvent.VK_ENTER){
               DefaultTableModel tr = (DefaultTableModel)Tabla1.getModel();
               tr.setRowCount(0); 
               int fila=Tabla2.getSelectedRow();
               Ccodserv.setText(Tabla2.getValueAt(fila,0).toString());
               Cservicio.setText(Tabla2.getValueAt(fila,1).toString());
               cargar_tabla();    
               Ficha.setSelectedIndex(0);
            }
        }//GEN-LAST:event_Tabla2KeyPressed

        private void btoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoncancelarActionPerformed
           DefaultTableModel tr = (DefaultTableModel)Tabla1.getModel();
           tr.setRowCount(0);
           aviso.setText("");
           swe = 0;
           limpiar();  
           btonmodificar.setEnabled(false);
           btoneliminar.setEnabled(false);
           btoncancelar.setEnabled(true);
           btonaceptar.setEnabled(false);
           btonsalir.setEnabled(true);    
           Ficha.setSelectedIndex(0);
        }//GEN-LAST:event_btoncancelarActionPerformed

        private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
           if ( swe == 0 ){
                permiso();
                btonmodificar.setEnabled(false);
                btoneliminar.setEnabled(false);
                btonaceptar.setEnabled(false);
           }
        }//GEN-LAST:event_formWindowActivated

private void Tabla3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabla3KeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER){  
         try { 
             String pcodigo = JOptionPane.showInputDialog("CODIGO SERVICIO:");
             int fila=Tabla3.getSelectedRow();
             String reporte = (Tabla3.getValueAt(fila,0).toString().trim());
             fileName ="./reporte/repbien.jasper";                
             Map parameters =new HashMap();               
             parameters.put("Nserv",pcodigo);
             JasperPrint jasperPrint = JasperFillManager.fillReport(fileName, parameters, conn1);
             JasperViewer leap = new JasperViewer(jasperPrint, false);
             leap.setTitle("Recibo de Soporte");
             leap.setVisible(true);
         } catch (JRException ex) {
             Logger.getLogger(bienes.class.getName()).log(Level.SEVERE, null, ex);
         }
      }
}//GEN-LAST:event_Tabla3KeyPressed

    private void permiso(){
         btonaceptar.setEnabled(false);
      if(txtopi.compareTo("0") == 0 )
        {btonincluir.setEnabled(false);}
       else
         btonincluir.setEnabled(true);
      if(txtopm.compareTo("0") == 0 )
        {btonmodificar.setEnabled(false);}
       else
         btonmodificar.setEnabled(true);
      if(txtope.compareTo("0") == 0 )
        {btoneliminar.setEnabled(false);}
       else
         btoneliminar.setEnabled(true);
    }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bienes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bien;
    private javax.swing.JLabel Btotal;
    private javax.swing.JLabel Bunitario;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JComboBox Ccodbien;
    private javax.swing.JFormattedTextField Ccodserv;
    private com.toedter.calendar.JDateChooser Cfecharec;
    private javax.swing.JTextField Cnumbien;
    private javax.swing.JTextField Cnumero;
    private javax.swing.JLabel Codigo;
    private javax.swing.JFormattedTextField Cservicio;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JTabbedPane Ficha;
    private javax.swing.JLabel Seccion;
    private javax.swing.JTable Tabla1;
    private javax.swing.JTable Tabla2;
    private javax.swing.JTable Tabla3;
    private javax.swing.JTextField aviso;
    private javax.swing.JButton btonaceptar;
    private javax.swing.JButton btoncancelar;
    private javax.swing.JButton btoneliminar;
    private javax.swing.JButton btonincluir;
    private javax.swing.JButton btonmodificar;
    private javax.swing.JButton btonsalir;
    private javax.swing.JFormattedTextField cantidad;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel fechareg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScroldescrip;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JFormattedTextField seccion;
    private javax.swing.JLabel servicio;
    private javax.swing.JFormattedTextField subgrupo;
    private javax.swing.JLabel subgrupos;
    private javax.swing.JScrollPane tabla1;
    private javax.swing.JFormattedTextField total;
    private javax.swing.JFormattedTextField unitario;
    // End of variables declaration//GEN-END:variables

    
}
