/*
 * consulta.java
 *
 * Created on 15 de agosto de 2008, 17:00
 */

package formas;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
 
/**
 *
 * @author  Ibrahin Araujo
 */
public class busqueda extends javax.swing.JFrame {
    public int swe = 0;
    private MiConexionBD cone;
    private java.sql.Statement stmt;     
    static  fsoporte MCORREPO = new fsoporte();
    static  busqueda MVER     = new busqueda();
    static  consulta BCON     = new consulta();   
    private String vtexto;
   

    /** Creates new form consulta */
    public busqueda() {
    
        try{              
             cone = cone.getInstance();
             Connection conn = cone.getMiConexion();
             stmt=conn.createStatement();             
          }
        
        catch(Exception e)
          {
          }
        initComponents();
        setIconImage (new ImageIcon("./imagenes/ibraico.png").getImage());
        setLocationRelativeTo(null);
        Ctexto.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ctexto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        Btonsalir = new javax.swing.JButton();
        btonrem = new javax.swing.JButton();
        Btondes = new javax.swing.JButton();
        Btondoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busqueda:Remitente,Destinatario y Documento");
        setAlwaysOnTop(true);
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel1.setText("Consulta:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 90, 22);

        Ctexto.setFont(new java.awt.Font("Arial", 1, 12));
        Ctexto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Ctexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CtextoMousePressed(evt);
            }
        });
        jPanel1.add(Ctexto);
        Ctexto.setBounds(100, 20, 490, 20);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaMouseReleased(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        tabla.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabla.getColumnModel().getColumn(1).setPreferredWidth(300);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 580, 210);

        Btonsalir.setFont(new java.awt.Font("Arial", 1, 12));
        Btonsalir.setText("Salir");
        Btonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtonsalirActionPerformed(evt);
            }
        });
        jPanel1.add(Btonsalir);
        Btonsalir.setBounds(500, 280, 90, 30);

        btonrem.setFont(new java.awt.Font("Tahoma", 1, 12));
        btonrem.setText("Remitente");
        btonrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonremActionPerformed(evt);
            }
        });
        jPanel1.add(btonrem);
        btonrem.setBounds(20, 280, 120, 30);

        Btondes.setFont(new java.awt.Font("Tahoma", 1, 12));
        Btondes.setText("Destinatario");
        Btondes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtondesActionPerformed(evt);
            }
        });
        jPanel1.add(Btondes);
        Btondes.setBounds(150, 280, 120, 30);

        Btondoc.setFont(new java.awt.Font("Tahoma", 1, 12));
        Btondoc.setText("Documento");
        Btondoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtondocActionPerformed(evt);
            }
        });
        jPanel1.add(Btondoc);
        Btondoc.setBounds(280, 280, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("static-access")
    private void tablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseReleased

       int fila=tabla.getSelectedRow();
       String codigo=tabla.getValueAt(fila,0).toString();
       String descrip=tabla.getValueAt(fila,1).toString();
       Ctexto.setText(descrip);

//      if(swe == 1) {
//       MCORREPO.mcode =  codigo;
//       MCORREPO.Ccodrem.setText(MCORREPO.mcode);
//       MCORREPO.mdes =  descrip;
//       MCORREPO.Cdenrem.setText(MCORREPO.mdes);
//      }
//      if(swe == 2) {
//       MCORREPO.mcode =  codigo;
//       MCORREPO.Ccoddes.setText(MCORREPO.mcode);
//       MCORREPO.mdes =  descrip;
//       MCORREPO.Cdendes.setText(MCORREPO.mdes);
//      }
//      if(swe == 3) {
//       MCORREPO.mcode =  codigo;
//       MCORREPO.Ccoddoc.setText(MCORREPO.mcode);
//       MCORREPO.mdes =  descrip;
//       MCORREPO.Cdendoc.setText(MCORREPO.mdes);
//       }
    }//GEN-LAST:event_tablaMouseReleased

    @SuppressWarnings("static-access")
    private void tablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyReleased
      int fila=tabla.getSelectedRow();
      String codigo=tabla.getValueAt(fila,0).toString();
      String descrip=tabla.getValueAt(fila,1).toString();
      Ctexto.setText(descrip);

//     if(swe == 1) {
//       MCORREPO.mcode =  codigo;
//       MCORREPO.Ccodrem.setText(MCORREPO.mcode);
//       MCORREPO.mdes =  descrip;
//       MCORREPO.Cdenrem.setText(MCORREPO.mdes);
//      }
//      if(swe == 2) {
//       MCORREPO.mcode =  codigo;
//       MCORREPO.Ccoddes.setText(MCORREPO.mcode);
//       MCORREPO.mdes =  descrip;
//       MCORREPO.Cdendes.setText(MCORREPO.mdes);
//      }
//      if(swe == 3) {
//       MCORREPO.mcode =  codigo;
//       MCORREPO.Ccoddoc.setText(MCORREPO.mcode);
//       MCORREPO.mdes =  descrip;
//       MCORREPO.Cdendoc.setText(MCORREPO.mdes);
//       }
    }//GEN-LAST:event_tablaKeyReleased

    @SuppressWarnings("static-access")
    private void BtonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtonsalirActionPerformed
     
      Ctexto.setText("");
//      MCORREPO.swe = 0;
      DefaultTableModel tr = (DefaultTableModel)tabla.getModel();
      tr.setRowCount(0);   
      setVisible(false);   
    }//GEN-LAST:event_BtonsalirActionPerformed

    private void btonremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonremActionPerformed
        swe = 1;
        vtexto  =  Ctexto.getText();

            DefaultTableModel tr = (DefaultTableModel)tabla.getModel();

             try
                {
               Statement s = cone.getMiConexion().createStatement();
               String consul="select * from remite where den_rem like '"+vtexto+"%'";
               ResultSet rs = s.executeQuery(consul);

                while (rs.next())
                    {
                      String var1 = rs.getString("cod_rem");
                      String var2 = rs.getString("den_rem");
                      tr.addRow(new Object[]{var1, var2,});
                      tabla.setModel(tr);
                      TableColumn column = null;
                      for (int i = 0; i < 2; i++) {
                        column = tabla.getColumnModel().getColumn(i);
                        if (i == 0) {column.setPreferredWidth(10);}
                        if (i == 1) {column.setPreferredWidth(430);}
                      }
                     }
             }

                catch (Exception e)
                {
                }
    }//GEN-LAST:event_btonremActionPerformed

    private void BtondesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtondesActionPerformed
        swe = 2;
        vtexto  =  Ctexto.getText();

            DefaultTableModel tr = (DefaultTableModel)tabla.getModel();

             try
                {

               Statement s = cone.getMiConexion().createStatement();
               String consul="select * from destina where den_des like '"+vtexto+"%'";
               ResultSet rs = s.executeQuery(consul);

                while (rs.next())
                    {
                      String var1 = rs.getString("cod_des");
                      String var2 = rs.getString("den_des");
                      tr.addRow(new Object[]{var1, var2,});
                      tabla.setModel(tr);
                      TableColumn column = null;
                      for (int i = 0; i < 2; i++) {
                        column = tabla.getColumnModel().getColumn(i);
                        if (i == 0) {column.setPreferredWidth(10);}
                        if (i == 1) {column.setPreferredWidth(430);}
                      }
                     }
             }

                catch (Exception e)
                {
                }
    }//GEN-LAST:event_BtondesActionPerformed

    private void BtondocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtondocActionPerformed
        swe = 3;
        vtexto  =  Ctexto.getText();

            DefaultTableModel tr = (DefaultTableModel)tabla.getModel();

             try
                {

               Statement s = cone.getMiConexion().createStatement();
               String consul="select * from documento where den_doc like '"+vtexto+"%'";
               ResultSet rs = s.executeQuery(consul);

                while (rs.next())
                    {
                      String var1 = rs.getString("cod_doc");
                      String var2 = rs.getString("den_doc");
                      tr.addRow(new Object[]{var1, var2,});
                      tabla.setModel(tr);
                      TableColumn column = null;
                      for (int i = 0; i < 2; i++) {
                        column = tabla.getColumnModel().getColumn(i);
                        if (i == 0) {column.setPreferredWidth(10);}
                        if (i == 1) {column.setPreferredWidth(430);}
                      }
                     }
             }

                catch (Exception e)
                {
                }
    }//GEN-LAST:event_BtondocActionPerformed

    private void CtextoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CtextoMousePressed
      swe = 0;
      Ctexto.setText("");
      DefaultTableModel tr = (DefaultTableModel)tabla.getModel();
      tr.setRowCount(0);
    }//GEN-LAST:event_CtextoMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                busqueda frame = new busqueda();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }
    
  
   public String cs(String a)
   {
       return "'"+a+"'";
   }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btondes;
    private javax.swing.JButton Btondoc;
    private javax.swing.JButton Btonsalir;
    private javax.swing.JTextField Ctexto;
    private javax.swing.JButton btonrem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
    
}
