/*
 * entrada.java
 *
 * Created on 23 de julio de 2008, 01:25 PM
 */

package formas;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;  
import javax.swing.JOptionPane;
/**
 *
 * @author  Ibrahin Araujo
 */

public class entrada extends javax.swing.JFrame {

    static Connection conn1 = null;
    private java.sql.Statement sql;
    private ResultSet rs;
    private String vencripta;
    public static String mcod_usr,mgrupo;
   

    /** Creates new form entrada */
   public entrada() {
     try{
            conn1 = (Connection) MiConexionBD.Enlace(conn1);
            sql   = conn1.createStatement();
           
          }        
        catch(Exception e)
          {
          }
           initComponents();
           setIconImage (new ImageIcon("./imagenes/ibraico.png").getImage());
           setLocationRelativeTo(null);
           limpiar();         
    }
      
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cuadro2 = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        clave = new javax.swing.JLabel();
        txtpswusr = new javax.swing.JPasswordField();
        btonaceptar = new javax.swing.JButton();
        btonsalir = new javax.swing.JButton();
        cuadro1 = new javax.swing.JPanel();
        Imagen2 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setTitle("Entrada al Sistema");
        setModalExclusionType(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SOPORTE TECNICO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 440, 30);

        cuadro2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cuadro2.setLayout(null);

        usuario.setFont(new java.awt.Font("Arial", 1, 18));
        usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usuario.setText("Usuario:");
        cuadro2.add(usuario);
        usuario.setBounds(10, 10, 74, 22);

        txtusuario.setFont(new java.awt.Font("Arial", 1, 18));
        txtusuario.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        txtusuario.setPreferredSize(new java.awt.Dimension(8, 25));
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusuarioKeyPressed(evt);
            }
        });
        cuadro2.add(txtusuario);
        txtusuario.setBounds(10, 30, 190, 25);

        clave.setFont(new java.awt.Font("Arial", 1, 18));
        clave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clave.setText("Clave:");
        cuadro2.add(clave);
        clave.setBounds(10, 60, 57, 22);

        txtpswusr.setFont(new java.awt.Font("Arial", 1, 18));
        txtpswusr.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        txtpswusr.setPreferredSize(new java.awt.Dimension(8, 25));
        txtpswusr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpswusrKeyPressed(evt);
            }
        });
        cuadro2.add(txtpswusr);
        txtpswusr.setBounds(10, 80, 190, 25);

        btonaceptar.setFont(new java.awt.Font("Tahoma", 1, 14));
        btonaceptar.setText("Entrada");
        btonaceptar.setToolTipText("Entrada al Sistema");
        btonaceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btonaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonaceptarActionPerformed(evt);
            }
        });
        cuadro2.add(btonaceptar);
        btonaceptar.setBounds(10, 120, 90, 50);

        btonsalir.setFont(new java.awt.Font("Tahoma", 1, 14));
        btonsalir.setText("Salida");
        btonsalir.setToolTipText("Salida del Sistema");
        btonsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btonsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btonsalir.setIconTextGap(0);
        btonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonsalirActionPerformed(evt);
            }
        });
        cuadro2.add(btonsalir);
        btonsalir.setBounds(106, 120, 90, 50);

        cuadro1.setBackground(new java.awt.Color(255, 255, 255));
        cuadro1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cuadro1.setLayout(null);

        Imagen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logohgs.jpg"))); // NOI18N
        Imagen2.setDoubleBuffered(true);
        Imagen2.setFocusCycleRoot(true);
        Imagen2.setFocusTraversalPolicyProvider(true);
        Imagen2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro1.add(Imagen2);
        Imagen2.setBounds(10, 10, 190, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuadro1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(cuadro2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuadro1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadro2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonsalirActionPerformed
        int a=JOptionPane.showConfirmDialog(this,"Desea salir del Sistema" +
                "","A T E N C I O N",JOptionPane.ERROR_MESSAGE);
        if(a==0) {
            try {
                try {
                    conn1.close();
                } catch (SQLException ex) {
                    Logger.getLogger(entrada.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.exit(0);
                rs.close();
                conn1.close();

            } catch (SQLException ex) {
                Logger.getLogger(entrada.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_btonsalirActionPerformed

    @SuppressWarnings("static-access")
    private void btonaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonaceptarActionPerformed

      try
       {
        vencripta = proceso.ENCRIPTAR(txtpswusr.getText());
        rs = sql.executeQuery("select * from admg02 where cod_usr='"+txtusuario.getText()+"' and psw_usr='"+vencripta+"' ");
        if(rs.next()){ // SI EL USUARIO EXISTE
           String valor;
           valor = rs.getString("edo_usu");
           if(valor.equals("B")) {
              JOptionPane.showMessageDialog(this,"EL USUARIO ESTA DESACTIVADO","COMUNIQUESE CON EL ADMINISTRADOR",JOptionPane.WARNING_MESSAGE);
              limpiar();
           } else {
                   menu.mcod_usr = rs.getString("cod_usr");
                   menu.Vusuario = rs.getString("den_usr");
                   menu.Vcedula  = rs.getString("cedula");
                   menu.conn1 = (com.mysql.jdbc.Connection) conn1;
                   menu.sql = sql;
                   proceso.sql=sql;
                   limpiar();
                   rs.close();
                   dispose();
                   new menu().setVisible(true);
                  }
           }
             else{
               JOptionPane.showMessageDialog(this,"USUARIO O CLAVE INCORRECTA","VUELVA A INTENTARLO",JOptionPane.INFORMATION_MESSAGE);
               limpiar();
        }
       }catch(Exception e)
           {}

}//GEN-LAST:event_btonaceptarActionPerformed

    private void txtusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            evt.setKeyCode(0);
            txtpswusr.requestFocus();
        }
    }//GEN-LAST:event_txtusuarioKeyPressed

    private void txtpswusrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpswusrKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            evt.setKeyCode(0);
            btonaceptar.doClick();
        }
    }//GEN-LAST:event_txtpswusrKeyPressed

private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtusuarioActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               JFrame frame = new entrada();
               frame.setLocationRelativeTo(null);
               frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);   
               frame.setVisible(true);
            }
        });
    }
   private void limpiar(){
       String valor = "";
       txtusuario.setText("");
       txtpswusr.setText("");
       txtusuario.requestFocus();
   }
   
       
//    static entrada ENTRA  = new entrada();
//    static menu ME = new menu();
//    static proceso PROCE = new proceso();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen2;
    private javax.swing.JButton btonaceptar;
    private javax.swing.JButton btonsalir;
    private javax.swing.JLabel clave;
    private javax.swing.JPanel cuadro1;
    private javax.swing.JPanel cuadro2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtpswusr;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
    
}
