/*
 * fempresa.java
 *
 * Created on 12 de agosto de 2008, 07:54 AM
 */
package formas;


import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author  Ibrahin araujo
 */
public class fempresa extends javax.swing.JFrame {

    public static java.sql.Statement sql;
    private ResultSet rs;
    private String Vopi,Vopm,Vope;
    public String  Nregistro,Mfecha;
    public static String txtopi,txtopm,txtope,mcode;
    private Date fechaing;  
    public int opcion;
    public  String fecreg;
    
    public fempresa() {
        try {
         
        } catch (Exception e) {
        }
        initComponents();
        setIconImage (new ImageIcon("./imagenes/ibraico.png").getImage());
        setLocationRelativeTo(null);
        buscar();
    }


    @SuppressWarnings("static-access")
    private void buscar() {
    
        try {
           
            rs = sql.executeQuery("select * from admg01 ");

            if (rs.next()) {
                Nregistro = (rs.getString("id"));
                txtcod_cia.setText(rs.getString("cod_cia"));
                txtslo_cia.setText(rs.getString("slo_cia"));
                txtden_cia.setText(rs.getString("den_cia"));
                txtciu_cia.setText(rs.getString("ciu_cia"));
                txtedo_cia.setText(rs.getString("edo_cia"));
                txtpai_cia.setText(rs.getString("pai_cia"));
                txtdir_cia.setText(rs.getString("dir_cia"));
                txtrif_cia.setText(rs.getString("rif_cia"));
                txtnit_cia.setText(rs.getString("nit_cia"));
                txttlf_cia.setText(rs.getString("tlf_cia"));
                txtpar_cia.setText(rs.getString("par_cia"));
                txtlogo.setText(rs.getString("logo"));


                 txtfec_reg.setDate(PROCE.Vfecha(rs.getDate("fec_reg")));

//                fechaing = rs.getDate("fec_reg");
//                SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
//                Mfecha =  sdf.format(fechaing);
//                if(Mfecha.compareTo("01/01/1900") ==0){
//                    txtfec_reg.setDate(null);
//                }else {
//                    txtfec_reg.setDate(fechaing);
//                }
            }
        } catch (Exception e) {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        btoneliminar = new javax.swing.JButton();
        btonaceptar = new javax.swing.JButton();
        btonsalir = new javax.swing.JButton();
        aviso = new javax.swing.JTextField();
        btonincluir = new javax.swing.JButton();
        btonmodificar = new javax.swing.JButton();
        btoncancelar = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcod_cia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtslo_cia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtden_cia = new javax.swing.JTextField();
        Panel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttlf_cia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtciu_cia = new javax.swing.JTextField();
        txtedo_cia = new javax.swing.JTextField();
        txtpai_cia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdir_cia = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        txtpar_cia = new javax.swing.JFormattedTextField();
        Panel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtnit_cia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtrif_cia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtfec_reg = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtlogo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registro de Empresa");
        setAlwaysOnTop(true);
        setIconImage(getIconImage());
        setResizable(false);

        Panel1.setBackground(new java.awt.Color(0, 102, 153));
        Panel1.setLayout(null);

        btoneliminar.setFont(new java.awt.Font("Arial", 1, 11));
        btoneliminar.setForeground(new java.awt.Color(0, 0, 102));
        btoneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminar.png"))); // NOI18N
        btoneliminar.setToolTipText("Eliminacion del Registro");
        btoneliminar.setMaximumSize(new java.awt.Dimension(55, 33));
        btoneliminar.setMinimumSize(new java.awt.Dimension(55, 33));
        btoneliminar.setPreferredSize(new java.awt.Dimension(55, 33));
        btoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoneliminarActionPerformed(evt);
            }
        });
        Panel1.add(btoneliminar);
        btoneliminar.setBounds(60, 4, 50, 50);

        btonaceptar.setFont(new java.awt.Font("Arial", 1, 11));
        btonaceptar.setForeground(new java.awt.Color(0, 0, 102));
        btonaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        btonaceptar.setToolTipText("Guadar Cambio");
        btonaceptar.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        btonaceptar.setMaximumSize(new java.awt.Dimension(87, 23));
        btonaceptar.setMinimumSize(new java.awt.Dimension(87, 23));
        btonaceptar.setPreferredSize(new java.awt.Dimension(87, 23));
        btonaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonaceptarActionPerformed(evt);
            }
        });
        Panel1.add(btonaceptar);
        btonaceptar.setBounds(210, 4, 50, 50);

        btonsalir.setFont(new java.awt.Font("Arial", 1, 11));
        btonsalir.setForeground(new java.awt.Color(0, 0, 102));
        btonsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btonsalir.setToolTipText("Salir");
        btonsalir.setPreferredSize(new java.awt.Dimension(83, 23));
        btonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonsalirActionPerformed(evt);
            }
        });
        Panel1.add(btonsalir);
        btonsalir.setBounds(260, 4, 50, 50);

        aviso.setFont(new java.awt.Font("Arial", 1, 12));
        aviso.setForeground(new java.awt.Color(0, 0, 153));
        aviso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aviso.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Panel1.add(aviso);
        aviso.setBounds(460, 18, 100, 20);

        btonincluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/incluir.png"))); // NOI18N
        btonincluir.setToolTipText("Ingreso de Nuevo Registro");
        btonincluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btonincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonincluirActionPerformed(evt);
            }
        });
        Panel1.add(btonincluir);
        btonincluir.setBounds(10, 4, 50, 50);

        btonmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btonmodificar.setToolTipText("Actualizacion del Registro");
        btonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonmodificarActionPerformed(evt);
            }
        });
        Panel1.add(btonmodificar);
        btonmodificar.setBounds(110, 4, 50, 50);

        btoncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/redo.png"))); // NOI18N
        btoncancelar.setToolTipText("cancelar registro");
        btoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoncancelarActionPerformed(evt);
            }
        });
        Panel1.add(btoncancelar);
        btoncancelar.setBounds(160, 4, 50, 50);

        Panel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Codigo");
        Panel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 38, 14);

        txtcod_cia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcod_cia.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Panel2.add(txtcod_cia);
        txtcod_cia.setBounds(70, 10, 30, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Slogan");
        Panel2.add(jLabel4);
        jLabel4.setBounds(310, 10, 40, 14);

        txtslo_cia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtslo_cia.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Panel2.add(txtslo_cia);
        txtslo_cia.setBounds(360, 10, 210, 18);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Nombre");
        Panel2.add(jLabel5);
        jLabel5.setBounds(10, 40, 50, 14);

        txtden_cia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtden_cia.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Panel2.add(txtden_cia);
        txtden_cia.setBounds(70, 40, 500, 18);

        Panel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Ciudad");
        Panel3.add(jLabel2);
        jLabel2.setBounds(10, 10, 38, 14);

        txttlf_cia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txttlf_cia.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Panel3.add(txttlf_cia);
        txttlf_cia.setBounds(70, 85, 190, 18);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Estado");
        Panel3.add(jLabel6);
        jLabel6.setBounds(10, 35, 50, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("Pais");
        Panel3.add(jLabel7);
        jLabel7.setBounds(10, 60, 23, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setText("Tlf No");
        Panel3.add(jLabel8);
        jLabel8.setBounds(10, 85, 31, 14);

        txtciu_cia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtciu_cia.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Panel3.add(txtciu_cia);
        txtciu_cia.setBounds(70, 10, 190, 18);

        txtedo_cia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtedo_cia.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Panel3.add(txtedo_cia);
        txtedo_cia.setBounds(70, 35, 190, 18);

        txtpai_cia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtpai_cia.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Panel3.add(txtpai_cia);
        txtpai_cia.setBounds(70, 60, 190, 18);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("Parroquia");
        Panel3.add(jLabel9);
        jLabel9.setBounds(270, 90, 60, 14);

        txtdir_cia.setColumns(20);
        txtdir_cia.setLineWrap(true);
        txtdir_cia.setRows(5);
        txtdir_cia.setWrapStyleWord(true);
        txtdir_cia.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        jScrollPane1.setViewportView(txtdir_cia);

        Panel3.add(jScrollPane1);
        jScrollPane1.setBounds(340, 10, 230, 70);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel13.setText("Direccion");
        Panel3.add(jLabel13);
        jLabel13.setBounds(270, 14, 60, 10);

        txtpar_cia.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Panel3.add(txtpar_cia);
        txtpar_cia.setBounds(340, 90, 230, 18);

        Panel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Nit. No");
        Panel4.add(jLabel3);
        jLabel3.setBounds(300, 10, 40, 14);

        txtnit_cia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtnit_cia.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Panel4.add(txtnit_cia);
        txtnit_cia.setBounds(340, 10, 190, 18);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setText("Rif. No");
        Panel4.add(jLabel10);
        jLabel10.setBounds(10, 10, 40, 14);

        txtrif_cia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtrif_cia.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Panel4.add(txtrif_cia);
        txtrif_cia.setBounds(70, 10, 190, 18);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText("Fec.Reg");
        Panel4.add(jLabel11);
        jLabel11.setBounds(10, 35, 50, 14);
        txtfec_reg = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "####-##-##", '_');
        txtfec_reg.setFont(new java.awt.Font("Tahoma", 0, 12));
        Panel4.add(txtfec_reg);
        txtfec_reg.setBounds(70, 35, 100, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setText("Logo");
        Panel4.add(jLabel12);
        jLabel12.setBounds(300, 40, 30, 14);

        txtlogo.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Panel4.add(txtlogo);
        txtlogo.setBounds(340, 38, 240, 18);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel3, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel4, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonsalirActionPerformed
        limpiar();
        dispose();
    }//GEN-LAST:event_btonsalirActionPerformed
public String Gfecha(Date f2){
       String fechaS;
       Date fecha1 = f2;
       if (fecha1 == null){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            try {
                fecha1  = sdf.parse("0001/01/01");             
            } catch (ParseException ex) {
                Logger.getLogger(fempresa.class.getName()).log(Level.SEVERE, null, ex);
            }
            fechaS = sdf.format(fecha1);
            }else {
              SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
              fechaS = sdf.format(fecha1);
       }       
       return fechaS;
}
    private void btonaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonaceptarActionPerformed
         //yyyy-MM-dd HH:mm:ss
        java.util.Date fecha = new Date();
        String fecreg1 = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(fecha);
        fecreg1 = (PROCE.fechasys(fecreg1));

        // Agregar Registro
        if (opcion == 1) {
        
            try {
               fecha();

               sql.executeUpdate("insert into admg01 (edo_reg," +
                                                     "cod_cia,"+
                                                     "slo_cia," +
                                                     "den_cia," +
                                                     "ciu_cia," +
                                                     "edo_cia," +
                                                     "pai_cia," +
                                                     "dir_cia," +
                                                     "rif_cia," +
                                                     "nit_cia," +
                                                     "tlf_cia," +
                                                     "par_cia," + 
                                                     "logo," +
                                                     "fec_reg)" +
                                             "values('A'," +
                                                    "txtcod_cia.getText()," +
                                                    "txtslo_cia.getText().toUpperCase()," +
                                                    "txtden_cia.getText().toUpperCase()," +
                                                    "txtciu_cia.getText().toUpperCase()," +
                                                    "txtedo_cia.getText().toUpperCase()," +
                                                    "txtpai_cia.getText().toUpperCase()," +
                                                    "txtdir_cia.getText()," +
                                                    "txtrif_cia.getText().toUpperCase()," +
                                                    "txtnit_cia.getText().toUpperCase()," +
                                                    "txttlf_cia.getText()," +
                                                    "txtpar_cia.getText().toUpperCase()," +                       
                                                    "txtlogo.getText().toUpperCase()," +
                                                    "fecreg1"); 
                 JOptionPane.showMessageDialog(this, "OPERACION EXITOSA", "A T E N C I O N.", JOptionPane.INFORMATION_MESSAGE);
               
            } catch (Exception e) {
            }
        }
     Date Xfecha;
        
        if (opcion == 2) {
            // Actualizar el Registro   
            
            
           int a=JOptionPane.showConfirmDialog(this,"Desea Modificar el Registro" +
                "","A T E N C I O N",JOptionPane.ERROR_MESSAGE);
            if (a == 0) {

                try {
                    fecha();
                   
                  sql.executeUpdate("update admg01 " +
                      " set cod_cia = '"+txtcod_cia.getText().trim()+"'"+
                      ",slo_cia     = '"+txtslo_cia.getText().toUpperCase().trim()+"'"+
                      ",den_cia     = '"+txtden_cia.getText().toUpperCase().trim()+"'"+
                      ",ciu_cia     = '"+txtciu_cia.getText().toUpperCase().trim()+"'"+ 
                      ",edo_cia     = '"+txtedo_cia.getText().toUpperCase().trim()+"'"+      
                      ",pai_cia     = '"+txtpai_cia.getText().toUpperCase().trim()+"'"+
                      ",dir_cia     = '"+txtdir_cia.getText().toUpperCase().trim()+"'"+      
                      ",rif_cia     = '"+txtrif_cia.getText().toUpperCase().trim()+"'"+ 
                      ",nit_cia     = '"+txtnit_cia.getText().toUpperCase().trim()+"'"+ 
                      ",tlf_cia     = '"+txttlf_cia.getText().toUpperCase().trim()+"'"+ 
                      ",par_cia     = '"+txtpar_cia.getText().toUpperCase().trim()+"'"+      
                      ",logo        = '"+txtlogo.getText().toUpperCase().trim()+"'"+  
                      ",fec_reg     = '"+PROCE.Gfecha(txtfec_reg.getDate())+"'"+      
                      "where id = '"+Nregistro+"'");


//                    sql.executeUpdate("UPDATE admg01 " + 
//                            " set  cod_cia  =" + txtcod_cia.getText().trim() +
//                            ",slo_cia  =" + txtslo_cia.getText().toUpperCase().trim() +
//                            ",den_cia  =" + txtden_cia.getText() +
//                            ",ciu_cia  =" + txtciu_cia.getText() +
//                            ",edo_cia  =" + txtedo_cia.getText() +
//                            ",pai_cia  =" + txtpai_cia.getText() +
//                            ",dir_cia  =" + txtdir_cia.getText() +
//                            ",rif_cia  =" + txtrif_cia.getText() +
//                            ",nit_cia  =" + txtnit_cia.getText() +
//                            ",tlf_cia  =" + txttlf_cia.getText() +
//                            ",par_cia  =" + txtpar_cia.getText() +
//                            ",logo     =" + txtlogo.getText()    +
//                            ",fec_reg  =" + fecreg1+
//                            " WHERE id ='" + Nregistro + "' ");

                    //   ",fec_reg  =" + cs(Mfecha)   +


                    JOptionPane.showMessageDialog(this, "OPERACION EXITOSA", "A T E N C I O N.", JOptionPane.INFORMATION_MESSAGE);
                    opcion = 0;
                    aviso.setText(" ");
                    limpiar();
                } catch (Exception e) {
                }
            }
        }

        if (opcion == 3) {
            // Eliminacion del Registro
            int a=JOptionPane.showConfirmDialog(this,"Desea Eliminar El Registro" +
                "","A T E N C I O N",JOptionPane.ERROR_MESSAGE);
            
            if (a == 0) {

                try {
                   
                    sql.executeUpdate("Update admg01 set edo_reg = 'D' where id = '" + Nregistro + "'");
                  

                    JOptionPane.showMessageDialog(this, "OPERACION EXITOSA", "A T E N C I O N.", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                }
            }
        }

        limpiar();
        buscar();
    }//GEN-LAST:event_btonaceptarActionPerformed

    private void btoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoneliminarActionPerformed
        opcion = 3;
        aviso.setText("ELIMINAR");
    }//GEN-LAST:event_btoneliminarActionPerformed

    private void btonincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonincluirActionPerformed
        opcion = 1;
        aviso.setText("INCLUIR");
    }//GEN-LAST:event_btonincluirActionPerformed

    private void btonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonmodificarActionPerformed
        opcion = 2;
        aviso.setText("MODIFICAR");
    }//GEN-LAST:event_btonmodificarActionPerformed

    private void btoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoncancelarActionPerformed
        opcion = 0;
        aviso.setText(" ");
        btonsalir.setEnabled(true);
        limpiar();
    }//GEN-LAST:event_btoncancelarActionPerformed
    
     public void limpiar() {
        txtcod_cia.setText("");
        txtslo_cia.setText("");
        txtden_cia.setText("");
        txtciu_cia.setText("");
        txtedo_cia.setText("");
        txtpai_cia.setText("");
        txtdir_cia.setText("");
        txtrif_cia.setText("");
        txtnit_cia.setText("");
        txttlf_cia.setText("");
        txtpar_cia.setText("");
        txtlogo.setText("");
        txtfec_reg.setDate(null);
        aviso.setText("");
    }

     private void fecha(){
     if (txtfec_reg.getDate()== null){
         fecreg = "1900-01-01";
       }else {
         fecreg = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(txtfec_reg.getDate());
         fecreg = (PROCE.Grabafecha(fecreg));
     }
     
   }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                JFrame empresa = new fempresa();
                empresa.setLocationRelativeTo(null);
                empresa.setVisible(true);
            }
        });
    }

     static proceso PROCE = new proceso();
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JTextField aviso;
    private javax.swing.JButton btonaceptar;
    private javax.swing.JButton btoncancelar;
    private javax.swing.JButton btoneliminar;
    private javax.swing.JButton btonincluir;
    private javax.swing.JButton btonmodificar;
    private javax.swing.JButton btonsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtciu_cia;
    private javax.swing.JTextField txtcod_cia;
    private javax.swing.JTextField txtden_cia;
    private javax.swing.JTextArea txtdir_cia;
    private javax.swing.JTextField txtedo_cia;
    private com.toedter.calendar.JDateChooser txtfec_reg;
    private javax.swing.JTextField txtlogo;
    public static javax.swing.JTextField txtnit_cia;
    private javax.swing.JTextField txtpai_cia;
    private javax.swing.JFormattedTextField txtpar_cia;
    private javax.swing.JTextField txtrif_cia;
    private javax.swing.JTextField txtslo_cia;
    private javax.swing.JTextField txttlf_cia;
    // End of variables declaration//GEN-END:variables

    


}
