/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fsoporte.java
 *
 * Created on 08-jun-2011, 6:45:30
 */
package formas;

import com.mysql.jdbc.Connection;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;



/**
 *
 * @author ibrahinaraujo
 */
public class fsoporte extends javax.swing.JFrame {
    public static Connection conn1;
    public static java.sql.Statement sql;
    private ResultSet rs;
    private int opcion;
    public  static int swe = 0;   
    public static String Nregistro,fecha ;    
    public static String txtopi,txtopm,txtope;
    public String fecrec,fecdes,fecconte,Mfecha,mcode,mdes,Medoreg,Void;    
    public static String fileName,mfila;
    proceso PROCE = new proceso();
    public Date d;
    
    /** Creates new form fsoporte */
    public fsoporte() {
           initComponents();
           setIconImage (new ImageIcon("./imagenes/ibraico.png").getImage());
           ((JPanelConFondo) panelFondo).setImagen("/imagenes/logohgs.jpg");
           setLocationRelativeTo(null);
           Cfecharec.requestFocus();
           JTableHeader cabeceraTabla1 = Tabla1.getTableHeader();
           cabeceraTabla1.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 12));
           cabeceraTabla1.setBackground(new java.awt.Color(0, 102, 153));
           cabeceraTabla1.setForeground(new java.awt.Color(255,255, 255));
           JTableHeader cabeceraTabla2 = Tabla2.getTableHeader();
           cabeceraTabla2.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 12));
           cabeceraTabla2.setBackground(new java.awt.Color(0, 102, 153));
           cabeceraTabla2.setForeground(new java.awt.Color(255,255, 255));   
           cargar_servicios();    
          
    }

    private String getDateTime() {
      DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
      Date date = new Date();
      return dateFormat.format(date);
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Ficha = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cdesequipo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Cdessoporte = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Cfecharec = new com.toedter.calendar.JDateChooser();
        Cfechasal = new com.toedter.calendar.JDateChooser();
        Cnoment = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Ccodbien = new javax.swing.JComboBox();
        Cnumbien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        Cnumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Ccodserv = new javax.swing.JFormattedTextField();
        Cservicio = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        Cnomrec = new javax.swing.JFormattedTextField();
        aviso = new javax.swing.JTextField();
        btonincluir = new javax.swing.JButton();
        btoneliminar = new javax.swing.JButton();
        btonmodificar = new javax.swing.JButton();
        btoncancelar = new javax.swing.JButton();
        btonaceptar = new javax.swing.JButton();
        btonsalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        Btonrefre = new javax.swing.JButton();
        panelFondo = new JPanelConFondo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("REGISTRO DE SOPORE TECNICO");
        setBackground(new java.awt.Color(0, 102, 153));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Codigo");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 12, 43, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Usuario");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 70, 45, 15);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(1));

        Cdesequipo.setColumns(20);
        Cdesequipo.setFont(new java.awt.Font("Arial", 1, 12));
        Cdesequipo.setLineWrap(true);
        Cdesequipo.setRows(5);
        Cdesequipo.setWrapStyleWord(true);
        jScrollPane1.setViewportView(Cdesequipo);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(140, 160, 330, 100);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Cdessoporte.setColumns(20);
        Cdessoporte.setFont(new java.awt.Font("Arial", 1, 12));
        Cdessoporte.setLineWrap(true);
        Cdessoporte.setRows(5);
        Cdessoporte.setWrapStyleWord(true);
        jScrollPane2.setViewportView(Cdessoporte);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(140, 270, 330, 100);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setText("Causa del Equipo");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 160, 120, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel11.setText("Analista de soporte");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 380, 130, 15);

        Cfecharec.setFont(new java.awt.Font("Tahoma", 1, 12));
        Cfecharec.setMinSelectableDate(new java.util.Date(-62135765898000L));
        Cfecharec = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "####-##-##", '_');
        Cfecharec.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel3.add(Cfecharec);
        Cfecharec.setBounds(240, 10, 110, 20);

        Cfechasal.setFont(new java.awt.Font("Tahoma", 1, 12));
        Cfechasal = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "####-##-##", '_');
        Cfechasal.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel3.add(Cfechasal);
        Cfechasal.setBounds(240, 40, 110, 20);

        Cnoment.setFont(new java.awt.Font("Arial", 1, 12));
        Cnoment.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        jPanel3.add(Cnoment);
        Cnoment.setBounds(140, 70, 230, 23);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setText("Entrada");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(188, 12, 50, 15);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel7.setText("Salida");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(190, 40, 40, 14);

        Ccodbien.setFont(new java.awt.Font("Tahoma", 1, 12));
        Ccodbien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BE", "BN" }));
        Ccodbien.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jPanel3.add(Ccodbien);
        Ccodbien.setBounds(140, 130, 70, 25);

        Cnumbien.setFont(new java.awt.Font("Arial", 1, 12));
        Cnumbien.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        jPanel3.add(Cnumbien);
        Cnumbien.setBounds(220, 130, 150, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Bien");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(12, 134, 26, 15);

        Tabla1.setFont(new java.awt.Font("Tahoma", 1, 12));
        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "oid", "BIEN", "CODIGO", "SERVICIO", "FECHA ENTRADA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Tabla1MouseReleased(evt);
            }
        });
        Tabla1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tabla1KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(Tabla1);
        Tabla1.getColumnModel().getColumn(0).setMinWidth(0);
        Tabla1.getColumnModel().getColumn(0).setPreferredWidth(0);
        Tabla1.getColumnModel().getColumn(0).setMaxWidth(0);
        Tabla1.getColumnModel().getColumn(1).setMinWidth(100);
        Tabla1.getColumnModel().getColumn(1).setPreferredWidth(100);
        Tabla1.getColumnModel().getColumn(1).setMaxWidth(100);
        Tabla1.getColumnModel().getColumn(2).setMinWidth(50);
        Tabla1.getColumnModel().getColumn(2).setPreferredWidth(50);
        Tabla1.getColumnModel().getColumn(2).setMaxWidth(50);
        Tabla1.getColumnModel().getColumn(4).setMinWidth(100);
        Tabla1.getColumnModel().getColumn(4).setPreferredWidth(100);
        Tabla1.getColumnModel().getColumn(4).setMaxWidth(100);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(490, 90, 410, 470);

        Cnumero.setBackground(new java.awt.Color(255, 255, 102));
        Cnumero.setEditable(false);
        Cnumero.setFont(new java.awt.Font("Arial", 1, 12));
        Cnumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cnumero.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        jPanel3.add(Cnumero);
        Cnumero.setBounds(140, 12, 40, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Servicio");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 100, 47, 15);

        Ccodserv.setBackground(new java.awt.Color(255, 255, 102));
        Ccodserv.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Ccodserv.setEditable(false);
        Ccodserv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ccodserv.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel3.add(Ccodserv);
        Ccodserv.setBounds(140, 100, 40, 23);

        Cservicio.setBackground(new java.awt.Color(255, 255, 102));
        Cservicio.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Cservicio.setEditable(false);
        Cservicio.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel3.add(Cservicio);
        Cservicio.setBounds(190, 100, 280, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel12.setText("Diagnostico");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 270, 125, 15);

        Cnomrec.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Cnomrec.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel3.add(Cnomrec);
        Cnomrec.setBounds(140, 380, 230, 23);

        aviso.setFont(new java.awt.Font("Arial", 1, 12));
        aviso.setForeground(new java.awt.Color(0, 0, 153));
        aviso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aviso.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jPanel3.add(aviso);
        aviso.setBounds(10, 440, 90, 21);

        btonincluir.setFont(new java.awt.Font("Tahoma", 1, 12));
        btonincluir.setForeground(new java.awt.Color(0, 0, 102));
        btonincluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/incluir.png"))); // NOI18N
        btonincluir.setText("Incluir");
        btonincluir.setToolTipText("Incluir Registro");
        btonincluir.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btonincluir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btonincluir.setIconTextGap(10);
        btonincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonincluirActionPerformed(evt);
            }
        });
        jPanel3.add(btonincluir);
        btonincluir.setBounds(110, 420, 120, 30);

        btoneliminar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btoneliminar.setForeground(new java.awt.Color(0, 0, 102));
        btoneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminar.png"))); // NOI18N
        btoneliminar.setText("Borrar");
        btoneliminar.setToolTipText("Eliminar Registro");
        btoneliminar.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btoneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btoneliminar.setMaximumSize(new java.awt.Dimension(87, 23));
        btoneliminar.setMinimumSize(new java.awt.Dimension(87, 23));
        btoneliminar.setPreferredSize(new java.awt.Dimension(87, 23));
        btoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoneliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btoneliminar);
        btoneliminar.setBounds(110, 450, 120, 30);

        btonmodificar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btonmodificar.setForeground(new java.awt.Color(0, 0, 102));
        btonmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btonmodificar.setText("Modificar");
        btonmodificar.setToolTipText("Modificar Registro");
        btonmodificar.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btonmodificar.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        btonmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btonmodificar.setIconTextGap(5);
        btonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonmodificarActionPerformed(evt);
            }
        });
        jPanel3.add(btonmodificar);
        btonmodificar.setBounds(230, 420, 120, 30);

        btoncancelar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btoncancelar.setForeground(new java.awt.Color(0, 51, 102));
        btoncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btoncancelar.setText("Cancelar");
        btoncancelar.setToolTipText("Cancelar Registro");
        btoncancelar.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btoncancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btoncancelar.setIconTextGap(8);
        btoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoncancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btoncancelar);
        btoncancelar.setBounds(230, 450, 120, 30);

        btonaceptar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btonaceptar.setForeground(new java.awt.Color(0, 0, 102));
        btonaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disk.png"))); // NOI18N
        btonaceptar.setText("Guardar");
        btonaceptar.setToolTipText("Aceptar Registro");
        btonaceptar.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btonaceptar.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        btonaceptar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btonaceptar.setIconTextGap(14);
        btonaceptar.setMaximumSize(new java.awt.Dimension(87, 23));
        btonaceptar.setMinimumSize(new java.awt.Dimension(87, 23));
        btonaceptar.setPreferredSize(new java.awt.Dimension(87, 23));
        btonaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonaceptarActionPerformed(evt);
            }
        });
        jPanel3.add(btonaceptar);
        btonaceptar.setBounds(350, 420, 120, 30);

        btonsalir.setFont(new java.awt.Font("Tahoma", 1, 12));
        btonsalir.setForeground(new java.awt.Color(0, 0, 102));
        btonsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btonsalir.setText("Salida");
        btonsalir.setToolTipText("Salir de Cargo");
        btonsalir.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btonsalir.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        btonsalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btonsalir.setIconTextGap(14);
        btonsalir.setPreferredSize(new java.awt.Dimension(83, 23));
        btonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonsalirActionPerformed(evt);
            }
        });
        jPanel3.add(btonsalir);
        btonsalir.setBounds(350, 450, 120, 30);

        Ficha.addTab("FICHA DE REGISTRO", jPanel3);

        jPanel4.setLayout(null);

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tabla2KeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(Tabla2);
        Tabla2.getColumnModel().getColumn(0).setMinWidth(100);
        Tabla2.getColumnModel().getColumn(0).setPreferredWidth(100);
        Tabla2.getColumnModel().getColumn(0).setMaxWidth(100);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(20, 50, 500, 430);

        Btonrefre.setFont(new java.awt.Font("Tahoma", 1, 12));
        Btonrefre.setForeground(new java.awt.Color(0, 51, 102));
        Btonrefre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Refresh24.png"))); // NOI18N
        Btonrefre.setText("Refrescar");
        Btonrefre.setBorder(new javax.swing.border.SoftBevelBorder(0));
        Btonrefre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtonrefreActionPerformed(evt);
            }
        });
        jPanel4.add(Btonrefre);
        Btonrefre.setBounds(340, 3, 180, 40);

        panelFondo.setBorder(javax.swing.BorderFactory.createEtchedBorder(0));
        panelFondo.setOpaque(false);
        panelFondo.setPreferredSize(new java.awt.Dimension(596, 292));

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        jPanel4.add(panelFondo);
        panelFondo.setBounds(536, 12, 350, 470);

        Ficha.addTab("SERVICIOS", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ficha, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Ficha, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 4, 930, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar(){
      Cnumero.setText(null);  
      Cfecharec.setDate(null);
      Cfechasal.setDate(null);
      Cnoment.setText(null);
      Cnomrec.setText(null);
//      Ccodserv.setText(null);
//      Cservicio.setText(null);       
      Ccodbien.setSelectedItem(null);
      Cnumbien.setText(null);
      Cdesequipo.setText(null);
      Cdessoporte.setText(null);        
      aviso.setText(null);
  }
    
   private void cargar_tabla() {
        String valor  =  Ccodserv.getText().trim();
        DefaultTableModel tr = (DefaultTableModel)Tabla1.getModel();
        try {      
             rs = sql.executeQuery("select * from soporte "
                  + "inner join servicios on(servicios.cod_serv = soporte.codserv)"
                  + " where soporte.codserv="+valor+" and soporte.edo_reg ='A' "
                  + "order by soporte.fecharec desc ");
             while (rs.next()) {
                    Integer vreg     = rs.getInt("oid");
                    String  vbien    = rs.getString("codbien")+"-"+rs.getString("numbien");
                    String  vcodserv = rs.getString("codserv");               
                    String  vdenserv = rs.getString("den_serv").trim();
                    String  vfecrec  = PROCE.Verfecha(rs.getDate("fecharec"));
                    tr.addRow(new Object[]{new Integer (vreg), vbien, vcodserv,vdenserv, vfecrec});
                    Tabla1.setModel(tr);
                    TableColumn column = null;
             }
            } catch (Exception e) { }
    }
   
   private void cargar_servicios() {
        DefaultTableModel tr = (DefaultTableModel)Tabla2.getModel();
        try {
             rs = sql.executeQuery("select * from servicios order by den_serv");
             while (rs.next()) {                                       
                    String vcodserv = rs.getString("cod_serv");
                    String vdenserv = rs.getString("den_serv").trim();                   
                    tr.addRow(new Object[]{vcodserv,vdenserv});
                    Tabla2.setModel(tr);
                    TableColumn column = null;
            }
            } catch (Exception e) { }            
        }
   
    public void buscar(String M1){
        try
          {    
           rs = sql.executeQuery("select * from soporte where oid="+M1+" "); 
           if(rs.next()) {              
              Cnumero.setText(rs.getString("oid")); 
              Cnoment.setText(rs.getString("noment"));
              Cnomrec.setText(rs.getString("nomrec"));
              Cnumbien.setText(rs.getString("numbien"));
              Cdesequipo.setText(rs.getString("desequipo").toUpperCase().trim());
              Cdessoporte.setText(rs.getString("dessoporte").toUpperCase().trim());
              Ccodbien.setSelectedItem(rs.getString("codbien"));
              Cfecharec.setDate(PROCE.Vfecha(rs.getDate("fecharec")));
              Cfechasal.setDate(PROCE.Vfecha(rs.getDate("fechasal")));            
          }
        }
        catch (Exception e) { }      
  }  
public String Gfecha(Date f2){
       String fechaS;
       Date fecha1 = f2;
       if (fecha1 == null){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            try {
                fecha1  = sdf.parse("0001/01/01");             
            } catch (ParseException ex) {
                Logger.getLogger(fsoporte.class.getName()).log(Level.SEVERE, null, ex);
            }
            fechaS = sdf.format(fecha1);
            }else {
              SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
              fechaS = sdf.format(fecha1);
       }       
       return fechaS;
}
    
    private void btonincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonincluirActionPerformed
      opcion = 1;
      aviso.setText("INCLUIR");
      btonmodificar.setEnabled(false);
      btoneliminar.setEnabled(false);
      btoncancelar.setEnabled(true);
      btonaceptar.setEnabled(true);
    }//GEN-LAST:event_btonincluirActionPerformed

    private void btoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoneliminarActionPerformed
      if ( swe != 0){
          opcion = 3;
          swe = 1;
          aviso.setText("ELIMINACION");
          btoncancelar.setEnabled(true);
          btonaceptar.setEnabled(true);
      }
}//GEN-LAST:event_btoneliminarActionPerformed

    private void btonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonmodificarActionPerformed
      if ( swe != 0){
          opcion = 2;
          swe = 1;
          aviso.setText("MODIFICAR");
          btoncancelar.setEnabled(true);
          btonaceptar.setEnabled(true);
        }//GEN-LAST:event_btonmodificarActionPerformed
    }
        private void btonaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonaceptarActionPerformed
                     
            // Ingreso de Registro
           
            if(opcion == 1) {      
             
                try {    
                                        
                    String vedoreg = "A";
                    String vnoment = Cnoment.getText().toUpperCase().trim();
                    String vnomrec = Cnomrec.getText().toUpperCase().trim();
                    String vcodserv= Ccodserv.getText();
                    String vcodbien= (String) Ccodbien.getSelectedItem();
                    String vnumbien= Cnumbien.getText();
                    String mcedula = menu.Vcedula;                    
                    String vdesequipo= Cdesequipo.getText().toUpperCase().trim();
                    String vdessoporte= Cdessoporte.getText().toUpperCase().trim();
                    String vfecharec=Gfecha(Cfecharec.getDate());
                    String vfechasal=Gfecha(Cfechasal.getDate());
         
                    sql.executeUpdate("insert into soporte (edo_reg,noment,nomrec,codserv,codbien,numbien,desequipo,dessoporte,fecharec,fechasal,cedula,tiempo) "+
                                   "values('"+vedoreg+"','"+vnoment+"','"+vnomrec+"','"+vcodserv+"','"+vcodbien+"','"+vnumbien+"','"+vdesequipo+"','"+vdessoporte+"','"+vfecharec+"','"+vfechasal+"','"+mcedula+"','"+getDateTime()+"')"); 
                    
                    JOptionPane.showMessageDialog(this,"OPERACION EXITOSA","A T E N C I O N",JOptionPane.INFORMATION_MESSAGE);
                 
                }            catch(Exception e) { }
            }
        
            
            // Actualizacion del Registro
            if(opcion == 2) {
                int fila=Tabla1.getSelectedRow();
                Integer Numero = (Integer) Tabla1.getValueAt(fila,0);
                int a=JOptionPane.showConfirmDialog(this,"Desea Modificar el Registro" +
                        "","A T E N C I O N",JOptionPane.ERROR_MESSAGE);
                if(a==0) {
                    opcion=0;
                    swe = 0;                 
                 
                    try {                                          
                        sql.executeUpdate("update soporte " +
                                       " set noment  = '"+Cnoment.getText().toUpperCase().trim()+"'"+
                                       ",nomrec      = '"+Cnomrec.getText().toUpperCase().trim()+"'"+
                                       ",codserv     = '"+Ccodserv.getText()+"'"+                                      
                                       ",desequipo   = '"+Cdesequipo.getText().toUpperCase().trim()+"'"+
                                       ",dessoporte  = '"+Cdessoporte.getText().toUpperCase().trim()+"'"+
                                       ",codbien     = '"+Ccodbien.getSelectedItem()+"'"+
                                       ",numbien     = '"+Cnumbien.getText()+"'"+
                                       ",cedula      = '"+menu.Vcedula+"'"+
                                       ",tiempo      = '"+getDateTime()+"'"+
                                       ",fecharec    = '"+Gfecha(Cfecharec.getDate())+"'"+
                                       ",fechasal    = '"+Gfecha(Cfechasal.getDate())+"'"+
                                    "where oid       = '"+Numero+"'");   
                        
                        JOptionPane.showMessageDialog(this,"OPERACION EXITOSA","A T E N C I O N",JOptionPane.INFORMATION_MESSAGE);
                    }                    
                    catch(Exception e) { }
                }
            }
            
            // Eliminacion del Registro
            if(opcion == 3) {
                int a=JOptionPane.showConfirmDialog(this,"Desea Eliminar el Registro" +
                        "","A T E N C I O N",JOptionPane.ERROR_MESSAGE);
                if(a==0) {
                    
                    try {                       
                                          
                        sql.executeUpdate("UPDATE soporte SET edo_reg  ='D' WHERE oid ='"+Cnumero.getText()+"' ");
                        
                        JOptionPane.showMessageDialog(this,"OPERACION EXITOSA","A T E N C I O N",JOptionPane.INFORMATION_MESSAGE);
                    }
                    
                    catch(Exception e) { }
                }
            }
            DefaultTableModel tr = (DefaultTableModel)Tabla1.getModel();
            tr.setRowCount(0);
            cargar_tabla();
            swe = 0;
            limpiar();
            
}//GEN-LAST:event_btonaceptarActionPerformed

        private void btonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonsalirActionPerformed
        try {
            limpiar();
            dispose();
            rs.close();          
        } catch (SQLException ex) {
            Logger.getLogger(fsoporte.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btonsalirActionPerformed

        private void Tabla1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabla1KeyReleased
            swe = 1;
            int fila=Tabla1.getSelectedRow();
            String vregi=Tabla1.getValueAt(fila,0).toString(); 
            String vcode=Tabla1.getValueAt(fila,2).toString();            
            String vdes=Tabla1.getValueAt(fila,3).toString(); 
            Nregistro = vregi;
            Ccodserv.setText(vcode);
            Cservicio.setText(vdes);            
            buscar(Nregistro);  
            permiso();
        }//GEN-LAST:event_Tabla1KeyReleased

        private void Tabla1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseReleased
            swe = 1;
            int fila=Tabla1.getSelectedRow();
            String vregi=Tabla1.getValueAt(fila,0).toString(); 
            String vcode=Tabla1.getValueAt(fila,2).toString();            
            String vdes=Tabla1.getValueAt(fila,3).toString(); 
            Nregistro = vregi;
            Ccodserv.setText(vcode);
            Cservicio.setText(vdes);            
            buscar(Nregistro);    
            permiso();
        }//GEN-LAST:event_Tabla1MouseReleased

        private void Tabla2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabla2KeyPressed
            if(evt.getKeyCode()==KeyEvent.VK_ENTER){
               DefaultTableModel tr = (DefaultTableModel)Tabla1.getModel();
               tr.setRowCount(0); 
               int fila=Tabla2.getSelectedRow();
               Ccodserv.setText(Tabla2.getValueAt(fila,0).toString());
               Cservicio.setText(Tabla2.getValueAt(fila,1).toString());
               cargar_tabla();    
               Ficha.setSelectedIndex(0);
            }
        }//GEN-LAST:event_Tabla2KeyPressed

        private void btoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoncancelarActionPerformed
           DefaultTableModel tr = (DefaultTableModel)Tabla1.getModel();
           tr.setRowCount(0);
           aviso.setText("");
           swe = 0;
           Ccodserv.setText(null);
           Cservicio.setText(null);   
           limpiar();  
           btonmodificar.setEnabled(false);
           btoneliminar.setEnabled(false);
           btoncancelar.setEnabled(true);
           btonaceptar.setEnabled(false);
           btonsalir.setEnabled(true);    
           Ficha.setSelectedIndex(0);
        }//GEN-LAST:event_btoncancelarActionPerformed

        private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
           if ( swe == 0 ){
                permiso();
                btonmodificar.setEnabled(false);
                btoneliminar.setEnabled(false);
                btonaceptar.setEnabled(false);
           }
        }//GEN-LAST:event_formWindowActivated
    
        private void BtonrefreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtonrefreActionPerformed
           DefaultTableModel tr = (DefaultTableModel)Tabla2.getModel();
           tr.setRowCount(0);
           cargar_servicios();
        }//GEN-LAST:event_BtonrefreActionPerformed

    private void permiso(){
         btonaceptar.setEnabled(false);
      if(txtopi.compareTo("0") == 0 )
        {btonincluir.setEnabled(false);}
       else
         btonincluir.setEnabled(true);
      if(txtopm.compareTo("0") == 0 )
        {btonmodificar.setEnabled(false);}
       else
         btonmodificar.setEnabled(true);
      if(txtope.compareTo("0") == 0 )
        {btoneliminar.setEnabled(false);}
       else
         btoneliminar.setEnabled(true);
    }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fsoporte().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btonrefre;
    private javax.swing.JComboBox Ccodbien;
    private javax.swing.JFormattedTextField Ccodserv;
    private javax.swing.JTextArea Cdesequipo;
    private javax.swing.JTextArea Cdessoporte;
    private com.toedter.calendar.JDateChooser Cfecharec;
    private com.toedter.calendar.JDateChooser Cfechasal;
    private javax.swing.JTextField Cnoment;
    private javax.swing.JFormattedTextField Cnomrec;
    private javax.swing.JTextField Cnumbien;
    private javax.swing.JTextField Cnumero;
    private javax.swing.JFormattedTextField Cservicio;
    private javax.swing.JTabbedPane Ficha;
    private javax.swing.JTable Tabla1;
    private javax.swing.JTable Tabla2;
    private javax.swing.JTextField aviso;
    private javax.swing.JButton btonaceptar;
    private javax.swing.JButton btoncancelar;
    private javax.swing.JButton btoneliminar;
    private javax.swing.JButton btonincluir;
    private javax.swing.JButton btonmodificar;
    private javax.swing.JButton btonsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables

    
}
