/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fsoporte.java
 *
 * Created on 08-jun-2011, 6:45:30
 */
package formas;

import com.mysql.jdbc.Connection;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;


/**
 *
 * @author ibrahinaraujo
 */
public class inventario extends javax.swing.JFrame {
    public static Connection conn1;
    public static java.sql.Statement sql;
    private ResultSet rs;
    private int opcion;
    public  static int swe = 0;
    public static String Nregistro,fecha ;    
    public static String txtopi,txtopm,txtope;
    public String fecrec,fecdes,fecconte,Mfecha,mcode,mdes,Medoreg,Void;    
    public static String fileName;
    proceso PROCE = new proceso();
    
    /** Creates new form fsoporte */
    public inventario() {
           initComponents();
           setIconImage (new ImageIcon("./imagenes/ibraico.png").getImage());
           setLocationRelativeTo(null);
           Cfecharec.requestFocus();
           JTableHeader cabeceraTabla1 = Tabla1.getTableHeader();
           cabeceraTabla1.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 12));
           cabeceraTabla1.setBackground(new java.awt.Color(0, 102, 153));
           cabeceraTabla1.setForeground(new java.awt.Color(255,255, 255));
           JTableHeader cabeceraTabla2 = Tabla2.getTableHeader();
           cabeceraTabla2.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 12));
           cabeceraTabla2.setBackground(new java.awt.Color(0, 102, 153));
           cabeceraTabla2.setForeground(new java.awt.Color(255,255, 255));   
           cargar_servicios();      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btonincluir = new javax.swing.JButton();
        btoneliminar = new javax.swing.JButton();
        btonmodificar = new javax.swing.JButton();
        btoncancelar = new javax.swing.JButton();
        btonaceptar = new javax.swing.JButton();
        btonsalir = new javax.swing.JButton();
        aviso = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Ficha = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Cfecharec = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        Ccodbien = new javax.swing.JComboBox();
        Cnumbien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        Cnumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Ccodserv = new javax.swing.JFormattedTextField();
        Cservicio = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        cpu = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        tarjeta = new javax.swing.JFormattedTextField();
        disco = new javax.swing.JFormattedTextField();
        memoria = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        dvd = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        impresora = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        teclado = new javax.swing.JFormattedTextField();
        mouse = new javax.swing.JFormattedTextField();
        corneta = new javax.swing.JFormattedTextField();
        monitor = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        regulador = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        sistema = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("REGISTRO DE EQUIPOS");
        setBackground(new java.awt.Color(0, 102, 153));
        setModalExclusionType(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(null);

        btonincluir.setFont(new java.awt.Font("Tahoma", 1, 12));
        btonincluir.setForeground(new java.awt.Color(0, 0, 102));
        btonincluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/incluir.png"))); // NOI18N
        btonincluir.setText("Incluir");
        btonincluir.setToolTipText("Incluir Registro");
        btonincluir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btonincluir.setIconTextGap(10);
        btonincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonincluirActionPerformed(evt);
            }
        });
        jPanel1.add(btonincluir);
        btonincluir.setBounds(10, 10, 120, 30);

        btoneliminar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btoneliminar.setForeground(new java.awt.Color(0, 0, 102));
        btoneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminar.png"))); // NOI18N
        btoneliminar.setText("Borrar");
        btoneliminar.setToolTipText("Eliminar Registro");
        btoneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btoneliminar.setMaximumSize(new java.awt.Dimension(87, 23));
        btoneliminar.setMinimumSize(new java.awt.Dimension(87, 23));
        btoneliminar.setPreferredSize(new java.awt.Dimension(87, 23));
        btoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btoneliminar);
        btoneliminar.setBounds(10, 50, 120, 30);

        btonmodificar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btonmodificar.setForeground(new java.awt.Color(0, 0, 102));
        btonmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btonmodificar.setText("Modificar");
        btonmodificar.setToolTipText("Modificar Registro");
        btonmodificar.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        btonmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btonmodificar.setIconTextGap(5);
        btonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonmodificarActionPerformed(evt);
            }
        });
        jPanel1.add(btonmodificar);
        btonmodificar.setBounds(10, 90, 120, 30);

        btoncancelar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btoncancelar.setForeground(new java.awt.Color(0, 51, 102));
        btoncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/redo.png"))); // NOI18N
        btoncancelar.setText("Cancelar");
        btoncancelar.setToolTipText("Cancelar Registro");
        btoncancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btoncancelar.setIconTextGap(0);
        btoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoncancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btoncancelar);
        btoncancelar.setBounds(10, 130, 120, 30);

        btonaceptar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btonaceptar.setForeground(new java.awt.Color(0, 0, 102));
        btonaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        btonaceptar.setText("Guardar");
        btonaceptar.setToolTipText("Aceptar Registro");
        btonaceptar.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        btonaceptar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btonaceptar.setIconTextGap(14);
        btonaceptar.setMaximumSize(new java.awt.Dimension(87, 23));
        btonaceptar.setMinimumSize(new java.awt.Dimension(87, 23));
        btonaceptar.setPreferredSize(new java.awt.Dimension(87, 23));
        btonaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonaceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btonaceptar);
        btonaceptar.setBounds(10, 170, 120, 30);

        btonsalir.setFont(new java.awt.Font("Tahoma", 1, 12));
        btonsalir.setForeground(new java.awt.Color(0, 0, 102));
        btonsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btonsalir.setText("Salida");
        btonsalir.setToolTipText("Salir de Cargo");
        btonsalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btonsalir.setIconTextGap(10);
        btonsalir.setPreferredSize(new java.awt.Dimension(83, 23));
        btonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btonsalir);
        btonsalir.setBounds(10, 210, 120, 30);

        aviso.setFont(new java.awt.Font("Arial", 1, 12));
        aviso.setForeground(new java.awt.Color(0, 0, 153));
        aviso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aviso.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jPanel1.add(aviso);
        aviso.setBounds(10, 400, 110, 21);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Codigo");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 12, 43, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setText("Disco duro");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 133, 80, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel11.setText("Impresora");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 250, 90, 15);

        Cfecharec.setFont(new java.awt.Font("Tahoma", 1, 12));
        Cfecharec.setMinSelectableDate(new java.util.Date(-62135765898000L));
        Cfecharec = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "####-##-##", '_');
        Cfecharec.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel3.add(Cfecharec);
        Cfecharec.setBounds(260, 10, 110, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setText("Fecha_Rec");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(188, 12, 70, 15);

        Ccodbien.setFont(new java.awt.Font("Tahoma", 1, 12));
        Ccodbien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BE", "BN" }));
        Ccodbien.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jPanel3.add(Ccodbien);
        Ccodbien.setBounds(140, 70, 55, 25);

        Cnumbien.setFont(new java.awt.Font("Arial", 1, 12));
        Cnumbien.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        jPanel3.add(Cnumbien);
        Cnumbien.setBounds(200, 70, 120, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Sistema ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(330, 220, 60, 20);

        Tabla1.setFont(new java.awt.Font("Tahoma", 1, 12));
        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "oid", "BIEN", "CODIGO", "SERVICIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Tabla1MouseReleased(evt);
            }
        });
        Tabla1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tabla1KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(Tabla1);
        Tabla1.getColumnModel().getColumn(0).setMinWidth(0);
        Tabla1.getColumnModel().getColumn(0).setPreferredWidth(0);
        Tabla1.getColumnModel().getColumn(0).setMaxWidth(0);
        Tabla1.getColumnModel().getColumn(1).setMinWidth(50);
        Tabla1.getColumnModel().getColumn(1).setPreferredWidth(50);
        Tabla1.getColumnModel().getColumn(1).setMaxWidth(50);
        Tabla1.getColumnModel().getColumn(2).setMinWidth(80);
        Tabla1.getColumnModel().getColumn(2).setPreferredWidth(80);
        Tabla1.getColumnModel().getColumn(2).setMaxWidth(80);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(10, 310, 580, 120);

        Cnumero.setBackground(new java.awt.Color(255, 255, 102));
        Cnumero.setEditable(false);
        Cnumero.setFont(new java.awt.Font("Arial", 1, 12));
        Cnumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cnumero.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        jPanel3.add(Cnumero);
        Cnumero.setBounds(140, 12, 40, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Servicio");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 40, 47, 15);

        Ccodserv.setBackground(new java.awt.Color(255, 255, 102));
        Ccodserv.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Ccodserv.setEditable(false);
        Ccodserv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ccodserv.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel3.add(Ccodserv);
        Ccodserv.setBounds(140, 40, 40, 23);

        Cservicio.setBackground(new java.awt.Color(255, 255, 102));
        Cservicio.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        Cservicio.setEditable(false);
        Cservicio.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel3.add(Cservicio);
        Cservicio.setBounds(190, 40, 320, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel12.setText("Memoria");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 162, 70, 15);

        cpu.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        cpu.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(cpu);
        cpu.setBounds(140, 190, 180, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Bien");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 70, 26, 15);

        tarjeta.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        try {
            tarjeta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("****************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tarjeta.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(tarjeta);
        tarjeta.setBounds(140, 100, 180, 23);

        disco.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        try {
            disco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("****************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        disco.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(disco);
        disco.setBounds(140, 130, 180, 23);

        memoria.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        try {
            memoria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("****************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        memoria.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(memoria);
        memoria.setBounds(140, 160, 180, 23);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel13.setText("Procesador");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 195, 90, 15);

        dvd.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        try {
            dvd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("****************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dvd.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(dvd);
        dvd.setBounds(140, 220, 180, 23);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel15.setText("DVD o CD");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 225, 90, 15);

        impresora.setColumns(20);
        impresora.setFont(new java.awt.Font("Arial", 1, 12));
        impresora.setLineWrap(true);
        impresora.setRows(5);
        impresora.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        jScrollPane1.setViewportView(impresora);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(140, 250, 320, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Tarjeta Madre");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 100, 90, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Teclado");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(330, 75, 50, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Mouse");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(330, 105, 50, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Cornetas");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(330, 134, 60, 15);

        teclado.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        try {
            teclado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("****************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        teclado.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(teclado);
        teclado.setBounds(400, 70, 190, 23);

        mouse.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        try {
            mouse.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("****************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        mouse.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(mouse);
        mouse.setBounds(400, 100, 190, 23);

        corneta.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        try {
            corneta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("****************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        corneta.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(corneta);
        corneta.setBounds(400, 130, 190, 23);

        monitor.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        try {
            monitor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("****************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        monitor.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(monitor);
        monitor.setBounds(400, 160, 190, 23);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Monitor");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(330, 164, 50, 15);

        regulador.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        try {
            regulador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("****************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        regulador.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(regulador);
        regulador.setBounds(400, 190, 190, 23);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Regulador");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(330, 194, 64, 15);

        sistema.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        try {
            sistema.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("****************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        sistema.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel3.add(sistema);
        sistema.setBounds(400, 220, 190, 23);

        Ficha.addTab("REGISTRO DEL BIEN", jPanel3);

        jPanel4.setLayout(null);

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tabla2KeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(Tabla2);
        Tabla2.getColumnModel().getColumn(0).setMinWidth(100);
        Tabla2.getColumnModel().getColumn(0).setPreferredWidth(100);
        Tabla2.getColumnModel().getColumn(0).setMaxWidth(100);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(20, 20, 570, 410);

        Ficha.addTab("SERVICIOS", jPanel4);

        jPanel2.add(Ficha);
        Ficha.setBounds(10, 10, 610, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar(){
      Cnumero.setText("");  
      Cfecharec.setDate(null);
      memoria.setText(null);
      tarjeta.setText(null);
      cpu.setText(null);
      Ccodserv.setText(null);
      Cservicio.setText(null);       
      Ccodbien.setSelectedItem(null);
      Cnumbien.setText(null);
      disco.setText(null);
      dvd.setText(null);
      impresora.setText(null);
      teclado.setText(null);
      mouse.setText(null);
      corneta.setText(null);
      monitor.setText(null);
      regulador.setText(null);
      sistema.setText(null);
      aviso.setText(null);
  }
    
   private void cargar_tabla() {
        String valor  =  Ccodserv.getText();
        DefaultTableModel tr = (DefaultTableModel)Tabla1.getModel();
        try {
             rs = sql.executeQuery("select * from inventario inner join servicios on(servicios.cod_serv = inventario.codserv) where inventario.codserv="+valor+" and inventario.edo_reg ='A'  ");
             while (rs.next()) {
                    Integer vreg     = rs.getInt("oid");
                    String  vbien    = rs.getString("codbien")+"-"+rs.getString("numbien");
                    String  vcodserv = rs.getString("codserv");
                    String  vdenserv = rs.getString("den_serv").trim();                   
                    tr.addRow(new Object[]{new Integer (vreg), vbien, vcodserv,vdenserv});
                    Tabla1.setModel(tr);
                    TableColumn column = null;
             }
            } catch (Exception e) { }
    }
   
   private void cargar_servicios() {
        DefaultTableModel tr = (DefaultTableModel)Tabla2.getModel();
        try {
             rs = sql.executeQuery("select * from servicios order by cod_serv");
             while (rs.next()) {                                       
                    String vcodserv = rs.getString("cod_serv");
                    String vdenserv = rs.getString("den_serv").trim();                   
                    tr.addRow(new Object[]{vcodserv,vdenserv});
                    Tabla2.setModel(tr);
                    TableColumn column = null;
            }
            } catch (Exception e) { }            
        }
   
    public void buscar(String M1){
        try
          {    
           rs = sql.executeQuery("select * from inventario where oid="+M1+" "); 
           if(rs.next()) {              
              Cnumero.setText(rs.getString("oid")); 
              Cfecharec.setDate(PROCE.Vfecha(rs.getDate("fecharec")));            
              Ccodbien.setSelectedItem(rs.getString("codbien"));
              Cnumbien.setText(rs.getString("numbien"));              
              tarjeta.setText(rs.getString("tarjetamadre").toUpperCase().trim());
              disco.setText(rs.getString("disco"));
              memoria.setText(rs.getString("memoria").toUpperCase().trim());
              cpu.setText(rs.getString("procesador"));              
              dvd.setText(rs.getString("dvdcd").toUpperCase().trim());
              impresora.setText(rs.getString("impresora").toUpperCase().trim());    
              teclado.setText(rs.getString("teclado").toUpperCase().trim());    
              mouse.setText(rs.getString("mouse").toUpperCase().trim());    
              corneta.setText(rs.getString("corneta").toUpperCase().trim());    
              monitor.setText(rs.getString("monitor").toUpperCase().trim());    
              regulador.setText(rs.getString("regulador").toUpperCase().trim()); 
              sistema.setText(rs.getString("sistema").toUpperCase().trim()); 
          }
        }
        catch (Exception e) { }      
  }  
public String Gfecha(Date f2){
       String fechaS;
       Date fecha1 = f2;
       if (fecha1 == null){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            try {
                fecha1  = sdf.parse("0001/01/01");             
            } catch (ParseException ex) {
                Logger.getLogger(proceso.class.getName()).log(Level.SEVERE, null, ex);
            }
            fechaS = sdf.format(fecha1);
            }else {
              SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
              fechaS = sdf.format(fecha1);
       }       
       return fechaS;
}
    
    private void btonincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonincluirActionPerformed
      opcion = 1;
      aviso.setText("INCLUIR");
      btonmodificar.setEnabled(false);
      btoneliminar.setEnabled(false);
      btoncancelar.setEnabled(true);
      btonaceptar.setEnabled(true);
    }//GEN-LAST:event_btonincluirActionPerformed

    private void btoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoneliminarActionPerformed
      if ( swe != 0){
          opcion = 3;
          swe = 1;
          aviso.setText("ELIMINACION");
          btoncancelar.setEnabled(true);
          btonaceptar.setEnabled(true);
      }
}//GEN-LAST:event_btoneliminarActionPerformed

    private void btonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonmodificarActionPerformed
      if ( swe != 0){
          opcion = 2;
          swe = 1;
          aviso.setText("MODIFICAR");
          btoncancelar.setEnabled(true);
          btonaceptar.setEnabled(true);
        }//GEN-LAST:event_btonmodificarActionPerformed
    }
        private void btonaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonaceptarActionPerformed
        
                      
            // Ingreso de Registro
           
            if(opcion == 1) {      
             
                try {           
                    String vedoreg = "A";
                    String vfecharec=Gfecha(Cfecharec.getDate());
                    String vcodserv= Ccodserv.getText();
                    String vcodbien= (String) Ccodbien.getSelectedItem();
                    String vnumbien= Cnumbien.getText();
                    String vimpresora = impresora.getText().toUpperCase().trim();
                    String vtarjeta= tarjeta.getText().toUpperCase().trim();                    
                    String vdisco= disco.getText().toUpperCase().trim();
                    String vmemoria= memoria.getText().toUpperCase().trim();
                    String vcpu= cpu.getText().toUpperCase().trim();
                    String vdvd= dvd.getText().toUpperCase().trim();
                    String vteclado = teclado.getText().toUpperCase().trim();
                    String vmouse= mouse.getText().toUpperCase().trim();
                    String vcorneta= corneta.getText().toUpperCase().trim();
                    String vmonitor= monitor.getText().toUpperCase().trim();
                    String vregulador= regulador.getText().toUpperCase().trim();
                    String vsistema= sistema.getText().toUpperCase().trim();
                    
                    sql.executeUpdate("insert into inventario (edo_reg,"
                                                            + "fecharec,"
                                                            + "codserv,"
                                                            + "codbien,"                                                           
                                                            + "numbien,"
                                                            + "impresora,"
                                                            + "tarjetamadre,"
                                                            + "disco,"
                                                            + "memoria,"
                                                            + "procesador,"
                                                            + "dvdcd,"
                                                            + "teclado,"
                                                            + "mouse,"
                                                            + "corneta,"
                                                            + "monitor,"
                                                            + "regulador," 
                                                            + "sistema) "+
                                                  "values('"+vedoreg+"',"
                                                            + "'"+vfecharec+"',"
                                                            + "'"+vcodserv+"',"
                                                            + "'"+vcodbien+"',"
                                                            + "'"+vnumbien+"',"
                                                            + "'"+vimpresora+"',"
                                                            + "'"+vtarjeta+"',"
                                                            + "'"+vdisco+"',"
                                                            + "'"+vmemoria+"',"
                                                            + "'"+vcpu+"',"
                                                            + "'"+vdvd+"',"
                                                            + "'"+vteclado+"',"
                                                            + "'"+vmouse+"',"
                                                            + "'"+vcorneta+"',"
                                                            + "'"+vmonitor+"',"
                                                            + "'"+vregulador+"',"
                                                            + "'"+vsistema+"')");
                 
                }            catch(Exception e) { }
            }
            
            // Actualizacion del Registro
            if(opcion == 2) {
                int fila=Tabla1.getSelectedRow();
                Integer Numero = (Integer) Tabla1.getValueAt(fila,0);                
                int a=JOptionPane.showConfirmDialog(this,"Desea Modificar el Registro" +
                        "","A T E N C I O N",JOptionPane.ERROR_MESSAGE);
                if(a==0) {
                    opcion=0;
                    swe = 0;
                    try {     

                        sql.executeUpdate("update inventario " +
                                       " set codserv = '"+Ccodserv.getText().toUpperCase().trim()+"'"+
                                       ",procesador  = '"+cpu.getText().toUpperCase().trim()+"'"+
                                       ",fecharec    = '"+Gfecha(Cfecharec.getDate())+"'"+
                                       ",codserv     = '"+Ccodserv.getText()+"'"+  
                                       ",codbien     = '"+Ccodbien.getSelectedItem()+"'"+
                                       ",numbien     = '"+Cnumbien.getText()+"'"+ 
                                       ",tarjetamadre= '"+tarjeta.getText().toUpperCase().trim()+"'"+
                                       ",disco       = '"+disco.getText().toUpperCase().trim()+"'"+
                                       ",memoria     = '"+memoria.getText().toUpperCase().trim()+"'"+
                                       ",dvdcd       = '"+dvd.getText().toUpperCase().trim()+"'"+
                                       ",impresora   = '"+impresora.getText().toUpperCase().trim()+"'"+
                                       ",teclado     = '"+teclado.getText().toUpperCase().trim()+"'"+
                                       ",mouse       = '"+mouse.getText().toUpperCase().trim()+"'"+
                                       ",corneta     = '"+corneta.getText().toUpperCase().trim()+"'"+
                                       ",monitor     = '"+monitor.getText().toUpperCase().trim()+"'"+                                                                            
                                       ",regulador   = '"+regulador.getText().toUpperCase().trim()+"'"+
                                       ",sistema     = '"+sistema.getText().toUpperCase().trim()+"'"+
                                    "where oid       = '"+Numero+"'");                        
                    }                    
                    catch(Exception e) { }
                }
            }
            
            // Eliminacion del Registro
            if(opcion == 3) {
                int a=JOptionPane.showConfirmDialog(this,"Desea Eliminar el Registro x" +
                        "","A T E N C I O N",JOptionPane.ERROR_MESSAGE);
                if(a==0) {
                    
                    try {                       
                                       
                        sql.executeUpdate("UPDATE inventario SET edo_reg  ='D' WHERE oid ='"+Nregistro +"' ");
                        
                        JOptionPane.showMessageDialog(this,"OPERACION EXITOSA","A T E N C I O N",JOptionPane.INFORMATION_MESSAGE);
                    }
                    
                    catch(Exception e) { }
                }
            }
            swe = 0;           
            DefaultTableModel tr = (DefaultTableModel)Tabla1.getModel();
            tr.setRowCount(0);
            cargar_tabla();
            limpiar();
}//GEN-LAST:event_btonaceptarActionPerformed

        private void btonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonsalirActionPerformed
        try {
            limpiar();
            dispose();
            rs.close();          
        } catch (SQLException ex) {
            Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btonsalirActionPerformed

        private void Tabla1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabla1KeyReleased
            swe = 1;
            int fila=Tabla1.getSelectedRow();
            String vregi=Tabla1.getValueAt(fila,0).toString(); 
            String vcode=Tabla1.getValueAt(fila,2).toString();            
            String vdes=Tabla1.getValueAt(fila,3).toString(); 
            Nregistro = vregi;
            Ccodserv.setText(vcode);
            Cservicio.setText(vdes);            
            buscar(Nregistro);  
            permiso();
        }//GEN-LAST:event_Tabla1KeyReleased

        private void Tabla1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseReleased
            swe = 1;
            int fila=Tabla1.getSelectedRow();
            String vregi=Tabla1.getValueAt(fila,0).toString(); 
            String vcode=Tabla1.getValueAt(fila,2).toString();            
            String vdes=Tabla1.getValueAt(fila,3).toString(); 
            Nregistro = vregi;
            Ccodserv.setText(vcode);
            Cservicio.setText(vdes);            
            buscar(Nregistro);    
            permiso();
        }//GEN-LAST:event_Tabla1MouseReleased

        private void Tabla2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabla2KeyPressed
            if(evt.getKeyCode()==KeyEvent.VK_ENTER){
               DefaultTableModel tr = (DefaultTableModel)Tabla1.getModel();
               tr.setRowCount(0); 
               int fila=Tabla2.getSelectedRow();
               Ccodserv.setText(Tabla2.getValueAt(fila,0).toString());
               Cservicio.setText(Tabla2.getValueAt(fila,1).toString());
               cargar_tabla();    
               Ficha.setSelectedIndex(0);
            }
        }//GEN-LAST:event_Tabla2KeyPressed

        private void btoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoncancelarActionPerformed
           DefaultTableModel tr = (DefaultTableModel)Tabla1.getModel();
           tr.setRowCount(0);
           aviso.setText("");
           swe = 0;
           limpiar();  
           btonmodificar.setEnabled(false);
           btoneliminar.setEnabled(false);
           btoncancelar.setEnabled(true);
           btonaceptar.setEnabled(false);
           btonsalir.setEnabled(true);    
           Ficha.setSelectedIndex(0);
        }//GEN-LAST:event_btoncancelarActionPerformed

        private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
           if ( swe == 0 ){
                permiso();
                btonmodificar.setEnabled(false);
                btoneliminar.setEnabled(false);
                btonaceptar.setEnabled(false);
           }
        }//GEN-LAST:event_formWindowActivated

    private void permiso(){
         btonaceptar.setEnabled(false);
      if(txtopi.compareTo("0") == 0 )
        {btonincluir.setEnabled(false);}
       else
         btonincluir.setEnabled(true);
      if(txtopm.compareTo("0") == 0 )
        {btonmodificar.setEnabled(false);}
       else
         btonmodificar.setEnabled(true);
      if(txtope.compareTo("0") == 0 )
        {btoneliminar.setEnabled(false);}
       else
         btoneliminar.setEnabled(true);
    }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Ccodbien;
    private javax.swing.JFormattedTextField Ccodserv;
    private com.toedter.calendar.JDateChooser Cfecharec;
    private javax.swing.JTextField Cnumbien;
    private javax.swing.JTextField Cnumero;
    private javax.swing.JFormattedTextField Cservicio;
    private javax.swing.JTabbedPane Ficha;
    private javax.swing.JTable Tabla1;
    private javax.swing.JTable Tabla2;
    private javax.swing.JTextField aviso;
    private javax.swing.JButton btonaceptar;
    private javax.swing.JButton btoncancelar;
    private javax.swing.JButton btoneliminar;
    private javax.swing.JButton btonincluir;
    private javax.swing.JButton btonmodificar;
    private javax.swing.JButton btonsalir;
    private javax.swing.JFormattedTextField corneta;
    private javax.swing.JFormattedTextField cpu;
    private javax.swing.JFormattedTextField disco;
    private javax.swing.JFormattedTextField dvd;
    private javax.swing.JTextArea impresora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JFormattedTextField memoria;
    private javax.swing.JFormattedTextField monitor;
    private javax.swing.JFormattedTextField mouse;
    private javax.swing.JFormattedTextField regulador;
    private javax.swing.JFormattedTextField sistema;
    private javax.swing.JFormattedTextField tarjeta;
    private javax.swing.JFormattedTextField teclado;
    // End of variables declaration//GEN-END:variables

    
}
