/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * menup.java
 *
 * Created on 14/01/2010, 01:23:52 PM
 */

package formas;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
/**
 *
 * @author Ibrahin Araujo
 */
public class menu extends javax.swing.JFrame {

    public static Connection conn1 ;
    public static java.sql.Statement sql;
    public static ResultSet rs;
    public static  String Vopi,Vopm,Vope,mcod_usr,Vgrupo,Vusuario,Vcedula;
    public static int Vid;
    proceso PROCE = new proceso();
        
    /** Creates new form menup */
    public menu() {
         super( "INFORMATICA SOPORTE TECNICO" );
         JPanel contenido = new JPanel();
         this.setContentPane(contenido);
         try{
            
          }

       catch(Exception e)
          {
          }
            initComponents();
            setIconImage (new ImageIcon("./imagenes/ibraico.png").getImage());
            setLocationRelativeTo(null);
            ((JPanelConFondo) panelFondo).setImagen("/imagenes/soporte.jpg");
            setExtendedState(menu.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new JPanelConFondo();
        jLabel2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MENU1 = new javax.swing.JMenu();
        SMSOPORTE = new javax.swing.JMenuItem();
        SMSERVI = new javax.swing.JMenuItem();
        SMEQUIPO = new javax.swing.JMenuItem();
        MENU2 = new javax.swing.JMenu();
        SMUSUARIO = new javax.swing.JMenuItem();
        SMEMPRE = new javax.swing.JMenuItem();
        MENU3 = new javax.swing.JMenu();
        SMLISTA = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Btoncalendario = new javax.swing.JMenuItem();
        Btoncalculadora = new javax.swing.JMenuItem();
        MENU4 = new javax.swing.JMenu();
        Mentra = new javax.swing.JMenuItem();
        MENU5 = new javax.swing.JMenu();
        SMAYUDA = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelFondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(-16777216,true), 1, true));
        panelFondo.setOpaque(false);
        panelFondo.setPreferredSize(new java.awt.Dimension(596, 292));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mavarez Maria");
        jLabel2.setAutoscrolls(true);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtusuario.setEditable(false);
        txtusuario.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtusuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtusuario.setText("text01");
        txtusuario.setBorder(null);
        txtusuario.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Medina Elimar");
        jLabel3.setAutoscrolls(true);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Mora Jesus");
        jLabel4.setAutoscrolls(true);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Jimenez Alirio ");
        jLabel5.setAutoscrolls(true);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addContainerGap(437, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addContainerGap(437, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addContainerGap(437, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        MENU1.setText("Archivos");
        MENU1.setFont(new java.awt.Font("Tahoma", 1, 12));

        SMSOPORTE.setText("Registro de Soporte");
        SMSOPORTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMSOPORTEActionPerformed(evt);
            }
        });
        MENU1.add(SMSOPORTE);

        SMSERVI.setText("Servicios");
        SMSERVI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMSERVIActionPerformed(evt);
            }
        });
        MENU1.add(SMSERVI);

        SMEQUIPO.setText("Registro de Equipos");
        SMEQUIPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMEQUIPOActionPerformed(evt);
            }
        });
        MENU1.add(SMEQUIPO);

        jMenuBar1.add(MENU1);

        MENU2.setText("Administrador");
        MENU2.setFont(new java.awt.Font("Tahoma", 1, 12));

        SMUSUARIO.setText("Administrador de Usuarios");
        SMUSUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMUSUARIOActionPerformed(evt);
            }
        });
        MENU2.add(SMUSUARIO);

        SMEMPRE.setText("Resgistro de Empresa");
        SMEMPRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMEMPREActionPerformed(evt);
            }
        });
        MENU2.add(SMEMPRE);

        jMenuBar1.add(MENU2);

        MENU3.setText("Informes");
        MENU3.setFont(new java.awt.Font("Tahoma", 1, 12));

        SMLISTA.setText("Listados");
        SMLISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMLISTAActionPerformed(evt);
            }
        });
        MENU3.add(SMLISTA);

        jMenuBar1.add(MENU3);

        jMenu2.setText("Herramientas");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 12));

        Btoncalendario.setFont(new java.awt.Font("Tahoma", 1, 12));
        Btoncalendario.setText("Calendario");
        Btoncalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoncalendarioActionPerformed(evt);
            }
        });
        jMenu2.add(Btoncalendario);

        Btoncalculadora.setFont(new java.awt.Font("Tahoma", 1, 12));
        Btoncalculadora.setText("Calculadora");
        Btoncalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoncalculadoraActionPerformed(evt);
            }
        });
        jMenu2.add(Btoncalculadora);

        jMenuBar1.add(jMenu2);

        MENU4.setText("Salir");
        MENU4.setFont(new java.awt.Font("Tahoma", 1, 12));

        Mentra.setText("Salida");
        Mentra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MentraActionPerformed(evt);
            }
        });
        MENU4.add(Mentra);

        jMenuBar1.add(MENU4);

        MENU5.setText("Ayuda");
        MENU5.setFont(new java.awt.Font("Tahoma", 1, 12));

        SMAYUDA.setText("Informacion de los analistas");
        SMAYUDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMAYUDAActionPerformed(evt);
            }
        });
        MENU5.add(SMAYUDA);

        jMenuBar1.add(MENU5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("static-access")
    private void SMSOPORTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMSOPORTEActionPerformed
        //*** REGISTRO DE SOPORTE ***
        String Musuario = mcod_usr;
        String Mforma   ="FSOPORTE";
        try {
            PROCE.seguridadFormas(Musuario, Mforma);
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        fsoporte.txtopi = Vopi;
        fsoporte.txtopm = Vopm;
        fsoporte.txtope = Vope;        
        fsoporte.conn1  = (com.mysql.jdbc.Connection) conn1;
        fsoporte.sql = sql;
        new fsoporte().setVisible( true );
    }//GEN-LAST:event_SMSOPORTEActionPerformed

    @SuppressWarnings("static-access")
    private void SMSERVIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMSERVIActionPerformed
        //*** SERVICIOS ***
        String Musuario = mcod_usr;
        String Mforma   ="SERVICIOS";
        try {
            PROCE.seguridadFormas(Musuario, Mforma);
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        servicios.txtopi = Vopi;
        servicios.txtopm = Vopm;
        servicios.txtope = Vope;
        servicios.sql = sql;
        servicios.conn1 = (com.mysql.jdbc.Connection) conn1;
        new servicios().setVisible( true );
}//GEN-LAST:event_SMSERVIActionPerformed

    @SuppressWarnings("static-access")   
    private void SMUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMUSUARIOActionPerformed
        //*** ADMINSITRADOR DE USUARIO ***
        String Musuario = mcod_usr;
        String Mforma   ="AUSUARIO";
        try {
            PROCE.seguridadFormas(Musuario, Mforma);
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        ausuario.sql = sql;
        ausuario.conn1 = (com.mysql.jdbc.Connection) conn1;
        new ausuario().setVisible(true);
}//GEN-LAST:event_SMUSUARIOActionPerformed

    private void SMEMPREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMEMPREActionPerformed
        fempresa.sql = sql;
        new fempresa().setVisible(true);
}//GEN-LAST:event_SMEMPREActionPerformed

    @SuppressWarnings("static-access")
    private void SMLISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMLISTAActionPerformed
        reporte.Mgrupo = Vgrupo;
        reporte.Musuario = Vusuario;
        new reporte().setVisible(true);
}//GEN-LAST:event_SMLISTAActionPerformed

    private void MentraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MentraActionPerformed
        setVisible(false);
        new entrada().setVisible(true);
}//GEN-LAST:event_MentraActionPerformed

    private void SMAYUDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMAYUDAActionPerformed
        new ayuda().setVisible(true);
}//GEN-LAST:event_SMAYUDAActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        txtusuario.setText("Usuario:"+" "+Vusuario.trim());
        seguridadMenus();
    }//GEN-LAST:event_formWindowActivated

    private void BtoncalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoncalendarioActionPerformed
        new Pfecha().setVisible(true);
    }//GEN-LAST:event_BtoncalendarioActionPerformed

    private void BtoncalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoncalculadoraActionPerformed
        new calculadora().setVisible(true);
    }//GEN-LAST:event_BtoncalculadoraActionPerformed

    private void SMEQUIPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMEQUIPOActionPerformed
       //*** REGISTRO DE EQUIPOS ***
        String Musuario = mcod_usr;
        String Mforma   ="INVENTARIO";
        try {
            PROCE.seguridadFormas(Musuario, Mforma);
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        inventario.txtopi = Vopi;
        inventario.txtopm = Vopm;
        inventario.txtope = Vope;        
        inventario.conn1  = (com.mysql.jdbc.Connection) conn1;
        inventario.sql = sql;
        new inventario().setVisible( true );
    }//GEN-LAST:event_SMEQUIPOActionPerformed
    
      //*------------------------------*
      //*---< Rutina de Seguridad  >---*
      //*------------------------------*
      public void seguridadMenus(){

          @SuppressWarnings("static-access")
          String mcodusr = mcod_usr;
        try
          {
            
           rs = sql.executeQuery("select * from admg03 Where edo_reg = 'A'  and cod_usr = '"+mcodusr+"'");           

           while (rs.next()) {
              String mind_rap = rs.getString("ind_rap");
              String mcod_prg = rs.getString("cod_prg");

             if (mcod_prg.compareTo("FSOPORTE") == 0)
               if (mind_rap.compareTo("T") == 0)
                    {SMSOPORTE.setEnabled(true);}
               else {SMSOPORTE.setEnabled(false);}
             if (mcod_prg.compareTo("SERVICIOS") == 0)
               if (mind_rap.compareTo("T") == 0)
                    {SMSERVI.setEnabled(true);}
               else {SMSERVI.setEnabled(false);}             
             if (mcod_prg.compareTo("AUSUARIO") == 0)
               if (mind_rap.compareTo("T") == 0)
                    {SMUSUARIO.setEnabled(true);}
               else {SMUSUARIO.setEnabled(false);}
              if (mcod_prg.compareTo("FEMPRESA") == 0)
               if (mind_rap.compareTo("T") == 0)
                    {SMEMPRE.setEnabled(true);}
               else {SMEMPRE.setEnabled(false);}            
             if (mcod_prg.compareTo("REPORTE") == 0)
               if (mind_rap.compareTo("T") == 0)
                    {SMLISTA.setEnabled(true);}
               else {SMLISTA.setEnabled(false);} 
             if (mcod_prg.compareTo("INVENTARIO") == 0)
               if (mind_rap.compareTo("T") == 0)
                    {SMEQUIPO.setEnabled(true);}
               else {SMEQUIPO.setEnabled(false);}
////          
             }
           }
             catch (Exception e)
            {
           }
   }
 

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Btoncalculadora;
    private javax.swing.JMenuItem Btoncalendario;
    private javax.swing.JMenu MENU1;
    private javax.swing.JMenu MENU2;
    private javax.swing.JMenu MENU3;
    private javax.swing.JMenu MENU4;
    private javax.swing.JMenu MENU5;
    private javax.swing.JMenuItem Mentra;
    private javax.swing.JMenuItem SMAYUDA;
    private javax.swing.JMenuItem SMEMPRE;
    private javax.swing.JMenuItem SMEQUIPO;
    private javax.swing.JMenuItem SMLISTA;
    private javax.swing.JMenuItem SMSERVI;
    private javax.swing.JMenuItem SMSOPORTE;
    private javax.swing.JMenuItem SMUSUARIO;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables

}
