/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * reportes.java
 * Ibrahin Araujo
 * Created on 28/11/2009, 05:59:04 AM
 */

package formas;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


 /**
 *
 * @author Ibrahin Araujo
 */
public class reporte extends javax.swing.JFrame {
   private MiConexionBD cone;
   private java.sql.Statement stmt;
   public static  String fileName;
   public  static String Mgrupo,Musuario,Mcoddoc,Mcoddes;

  
    /** Creates new form reportes */
    public reporte() {
       JPanel contenido = new JPanel();
       this.setContentPane(contenido);
       try{
//             cone = cone.getInstance();
             //cone.init();
             //Connection conn = (Connection) MiConexionBD.getMiConexion();
//             stmt = cone.getSql();
             BufferedImage tmpImagen = ImageIO.read( getClass().getResource("/imagenes/fondoimpre.jpg" ));
             BgBorder fondo = new BgBorder( tmpImagen );
             contenido.setBorder(fondo);
          }

       catch(Exception e)
          {e.printStackTrace();}
            initComponents();
            setIconImage (new ImageIcon("./imagenes/ibraico.png").getImage());
            setLocationRelativeTo(null);
//            cargar_busqueda() ;           
    }

 
//    private void cargar_busqueda()
//    {
//       DefaultTableModel tr = (DefaultTableModel)tabla.getModel();
//         
//       try
//         {
//               Statement s = (Statement) cone.getMiConexion().createStatement();
//               String consul="select codigo,descrip from repolist where edo_reg='A'";
//               ResultSet rs = s.executeQuery(consul);
//
//                while (rs.next())
//                    {
//                      String var1 = rs.getString("codigo");
//                      String var2 = rs.getString("descrip");                    
//                      tr.addRow(new Object[]{var1, var2,});
//                      tabla.setModel(tr);
//                      TableColumn column = null;
//                      for (int i = 0; i < 1; i++) {
//                        column = tabla.getColumnModel().getColumn(i);
//                        if (i == 0) {column.setPreferredWidth(0);}
//                        if (i == 1) {column.setPreferredWidth(150);}                       
//                       }
//                    }
//         }
//             catch (Exception e)
//         { }
//   }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btonrepo = new javax.swing.JButton();
        Btonsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de Soporte Tecnico");
        setIconImage(getIconImage());
        setResizable(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 406));

        tabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Informe mensual general"},
                {null, "Informe mensual por usuario"},
                {null, "Informe de equipos pendientes"},
                {null, "Informe de equipos reparados"},
                {null, "Informe de equipos"}
            },
            new String [] {
                "CODIGO", "DESCRIPCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setRowHeight(20);
        tabla.getTableHeader().setResizingAllowed(false);
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setMinWidth(0);
            tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabla.getColumnModel().getColumn(0).setMaxWidth(0);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        btonrepo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btonrepo.setForeground(new java.awt.Color(0, 0, 102));
        btonrepo.setText("Mostrar Reporte");
        btonrepo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btonrepo.setContentAreaFilled(false);
        btonrepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonrepoActionPerformed(evt);
            }
        });

        Btonsalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btonsalir.setForeground(new java.awt.Color(0, 0, 102));
        Btonsalir.setText("Salir");
        Btonsalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btonsalir.setContentAreaFilled(false);
        Btonsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtonsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btonrepo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(Btonsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btonrepo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btonsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btonrepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonrepoActionPerformed
        Map paremeters = null;
        switch (tabla.getSelectedRow()) {
            case 0:
                break;
            case 1:
                break;
            case 2:
                break;
            case 3:
                break;
            case 4:
                paremeters = new HashMap();
                paremeters.put("logo", getClass().getResourceAsStream("/imagenes/logohgs.jpg"));
                print(getClass().getResource("/reporte/ListadoEquipos.jasper"), paremeters);
                break;
            default:
                JOptionPane.showMessageDialog(this, "  Elija una fila de Lista ", "A T E N C I O N", JOptionPane.PLAIN_MESSAGE);
        }
            
             
            
       
}//GEN-LAST:event_btonrepoActionPerformed
    
    private void BtonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtonsalirActionPerformed
        this.dispose();
}//GEN-LAST:event_BtonsalirActionPerformed
/**
 * @param args the command line arguments
*/
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btonsalir;
    private javax.swing.JButton btonrepo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
    
    private void print(URL fileName, Map parameters) {
        try {
            JasperReport report = (JasperReport) JRLoader.loadObject(fileName);
            JasperPrint print = JasperFillManager.fillReport(report, parameters, MiConexionBD.MiConexion);
            JasperViewer.viewReport(print, false);
        } catch (JRException ex) {
            Logger.getLogger(reporte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
